import { SessionClient, SessionClientError } from "@/modules/auth/api/sessionClient";

export interface RequirementVersionCreateInput {
  readonly initial: boolean; readonly base_version_ref: string | null; readonly title: string | null;
  readonly statement: string; readonly rationale: string; readonly domain_name: string;
  readonly priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT"; readonly risk: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  readonly classification: "STANDARD_FUNCTION" | "NONSTANDARD_FUNCTION" | "DIFFERENCE" | "PENDING_CONFIRMATION";
  readonly sources: readonly { readonly source_type: "APPROVED_SURVEY_CONCLUSION" | "CONFIRMED_HANDOVER" | "HUMAN_DECISION" | "PROJECT_EVIDENCE";
    readonly source_object_id: string; readonly source_version_ref: string | null; readonly evidence_refs: readonly string[] }[];
  readonly acceptance_criteria: readonly { readonly observable_result: string; readonly verification_method: string;
    readonly required_data: string; readonly required_environment: string; readonly evidence_requirement: string }[];
  readonly capability_assessments: readonly { readonly baseline_version_id: string; readonly capability_item_id: string;
    readonly match_type: "DIRECT" | "PARTIAL" | "NONE" | "UNKNOWN"; readonly fit_gap: string; readonly constraints_text: string;
    readonly assessor_kind: "HUMAN"; readonly confirmation_state: "CANDIDATE" | "CONFIRMED" | "REJECTED";
    readonly evidence_refs: readonly { readonly evidence_id: string; readonly evidence_role: string }[] }[];
  readonly assumptions: readonly string[]; readonly exclusions: readonly string[]; readonly dependencies: readonly string[];
  readonly ai_task_refs: readonly string[]; readonly client_reason: string;
}
export interface CreatedRequirementVersion { readonly requirement_version_id: string; readonly requirement_id: string;
  readonly project_id: string; readonly version_no: number; readonly state: "DRAFT"; readonly content_fingerprint: string;
  readonly supersedes_version_ref: string | null; readonly created_by: string; readonly created_at: string; readonly requirement_etag: string; }
export interface RequirementValidationReport { readonly audit_event_id: string; readonly requirement_id: string;
  readonly requirement_version_id: string; readonly project_id: string; readonly version_no: number; readonly state: "DRAFT";
  readonly classification: RequirementVersionCreateInput["classification"]; readonly valid: boolean;
  readonly blocking_issues: readonly string[]; readonly warnings: readonly string[]; readonly coverage_summary: Readonly<Record<string, number>>;
  readonly checked_at: string; }
export interface RequirementReviewSubmission { readonly review_id: string; readonly review_round_id: string; readonly subject_type: "REQ-03";
  readonly project_id: string; readonly requirement_id: string; readonly requirement_version_id: string; readonly policy_ref: "REQUIREMENT_ALL_V1";
  readonly reviewer_ids: readonly string[]; readonly state: "IN_REVIEW"; readonly round_no: number; readonly review_etag: string;
  readonly submitted_by: string; readonly submitted_at: string; }

const messages = { REQUIREMENT_WRITE_INVALID_INPUT: "需求版本输入不完整或格式无效。", AUTH_RELOGIN_REQUIRED: "写入需求前请重新登录。",
  AUTH_CLIENT_BUSY: "正在处理其他会话操作，请稍候。", AUTH_SESSION_EXPIRED: "会话已失效，请重新登录。", AUTH_CSRF_INVALID: "登录状态已变化，请重新登录。",
  LICENSE_OPERATION_DENIED: "当前许可不允许修改项目需求。", RESOURCE_NOT_FOUND: "需求不存在，或当前账户无权操作。", PROJECT_ARCHIVED: "项目已归档，不能再修改需求。",
  CONFLICT_VERSION: "需求已被其他操作更新，请重新读取。", CONFLICT_IDEMPOTENCY: "原操作号与本次输入不一致，已停止提交。", CONFLICT_STATE: "当前需求状态不允许此操作。",
  BUSINESS_REVIEW_NOT_ELIGIBLE: "需求版本尚未通过校验，不能送审。", REVIEW_REVIEWER_INELIGIBLE: "所选评审人不具备当前项目评审资格。", REVIEW_SUBJECT_LOCKED: "需求版本正在评审或已被锁定。",
  REQUIREMENT_WRITE_UNAVAILABLE: "暂时无法确认需求写入结果；请保留原操作并核对当前版本和审计。" } as const;
export type RequirementWriteErrorCode = keyof typeof messages;
export class RequirementVersionWriteError extends Error { readonly uncertain: boolean; constructor(readonly code: RequirementWriteErrorCode) {
  super(messages[code]); this.name = "RequirementVersionWriteError"; this.uncertain = code === "REQUIREMENT_WRITE_UNAVAILABLE"; } }
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/; const etag = /^"v(0|[1-9][0-9]*)"$/;
const digest = /^[0-9a-f]{64}$/; const issue = /^[A-Z][A-Z0-9_]{0,63}$/;
function record(v: unknown): v is Record<string, unknown> { return typeof v === "object" && v !== null && !Array.isArray(v); }
function exact(v: Record<string, unknown>, keys: readonly string[]) { return Object.keys(v).length === keys.length && keys.every(k => Object.hasOwn(v,k)); }
function id(v: unknown): v is string { return typeof v === "string" && uuid.test(v) && v !== "00000000-0000-0000-0000-000000000000"; }
function instant(v: unknown): v is string { return typeof v === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?Z$/.test(v) && Number.isFinite(Date.parse(v)); }
function integer(v: unknown, min=0) { return typeof v === "number" && Number.isSafeInteger(v) && v >= min; }
function text(v: unknown, max=4000): v is string { return typeof v === "string" && v.length > 0 && v.length <= max && v.trim() === v && !/\p{C}/u.test(v); }
function envelope(v: unknown): unknown { if (!record(v) || !exact(v,["data","trace_id"]) || !id(v.trace_id)) throw new RequirementVersionWriteError("REQUIREMENT_WRITE_UNAVAILABLE"); return v.data; }
async function payload(response: Response) { if (response.headers.get("content-type")?.split(";",1)[0].trim().toLowerCase() !== "application/json") throw new RequirementVersionWriteError("REQUIREMENT_WRITE_UNAVAILABLE"); try { return await response.json() as unknown; } catch { throw new RequirementVersionWriteError("REQUIREMENT_WRITE_UNAVAILABLE"); } }
function failure(status:number,v:unknown):never { const raw=record(v)&&record(v.error)&&typeof v.error.code==="string"?v.error.code:"";
  const known:Record<string,RequirementWriteErrorCode>={AUTH_SESSION_EXPIRED:"AUTH_SESSION_EXPIRED",AUTH_CSRF_INVALID:"AUTH_CSRF_INVALID",LICENSE_OPERATION_DENIED:"LICENSE_OPERATION_DENIED",RESOURCE_NOT_FOUND:"RESOURCE_NOT_FOUND",PROJECT_ARCHIVED:"PROJECT_ARCHIVED",CONFLICT_VERSION:"CONFLICT_VERSION",CONFLICT_IDEMPOTENCY:"CONFLICT_IDEMPOTENCY",CONFLICT_STATE:"CONFLICT_STATE",BUSINESS_REVIEW_NOT_ELIGIBLE:"BUSINESS_REVIEW_NOT_ELIGIBLE",REVIEW_REVIEWER_INELIGIBLE:"REVIEW_REVIEWER_INELIGIBLE",REVIEW_SUBJECT_LOCKED:"REVIEW_SUBJECT_LOCKED"};
  if(raw==="VALIDATION_FAILED"||status===400||status===422) throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT"); throw new RequirementVersionWriteError(known[raw]??"REQUIREMENT_WRITE_UNAVAILABLE"); }
function ids(...values:string[]) { if(values.some(v=>!id(v))) throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT"); }
function createInput(v:RequirementVersionCreateInput) { if(!record(v)||!exact(v,["initial","base_version_ref","title","statement","rationale","domain_name","priority","risk","classification","sources","acceptance_criteria","capability_assessments","assumptions","exclusions","dependencies","ai_task_refs","client_reason"])
  ||typeof v.initial!=="boolean"||v.base_version_ref!==null&&!id(v.base_version_ref)||v.title!==null&&!text(v.title,255)||!text(v.statement,20000)||!text(v.rationale,20000)||!text(v.domain_name,255)||!(["LOW","MEDIUM","HIGH","URGENT"] as unknown[]).includes(v.priority)||!(["LOW","MEDIUM","HIGH","CRITICAL"] as unknown[]).includes(v.risk)||!(["STANDARD_FUNCTION","NONSTANDARD_FUNCTION","DIFFERENCE","PENDING_CONFIRMATION"] as unknown[]).includes(v.classification)
  ||!Array.isArray(v.sources)||!Array.isArray(v.acceptance_criteria)||!Array.isArray(v.capability_assessments)||!Array.isArray(v.assumptions)||!Array.isArray(v.exclusions)||!Array.isArray(v.dependencies)||!Array.isArray(v.ai_task_refs)||!text(v.client_reason,2000)) throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT");
  for(const s of v.sources){if(!record(s)||!exact(s,["source_type","source_object_id","source_version_ref","evidence_refs"])||!(["APPROVED_SURVEY_CONCLUSION","CONFIRMED_HANDOVER","HUMAN_DECISION","PROJECT_EVIDENCE"] as unknown[]).includes(s.source_type)||!id(s.source_object_id)||s.source_version_ref!==null&&!id(s.source_version_ref)||!Array.isArray(s.evidence_refs)||s.evidence_refs.some(x=>!id(x))||(s.source_type==="CONFIRMED_HANDOVER")!==(s.source_version_ref!==null))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT");}
  for(const a of v.acceptance_criteria){if(!record(a)||!exact(a,["observable_result","verification_method","required_data","required_environment","evidence_requirement"])||Object.values(a).some(x=>!text(x)))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT");}
  for(const a of v.capability_assessments){if(!record(a)||!exact(a,["baseline_version_id","capability_item_id","match_type","fit_gap","constraints_text","assessor_kind","confirmation_state","evidence_refs"])||!id(a.baseline_version_id)||!id(a.capability_item_id)||!(["DIRECT","PARTIAL","NONE","UNKNOWN"] as unknown[]).includes(a.match_type)||!text(a.fit_gap)||!text(a.constraints_text)||a.assessor_kind!=="HUMAN"||!(["CANDIDATE","CONFIRMED","REJECTED"] as unknown[]).includes(a.confirmation_state)||!Array.isArray(a.evidence_refs)||a.evidence_refs.length!==2||a.evidence_refs.some(x=>!record(x)||!exact(x,["evidence_id","evidence_role"])||!id(x.evidence_id)||!(["STANDARD","PROJECT"] as unknown[]).includes(x.evidence_role))||new Set(a.evidence_refs.map(x=>x.evidence_role)).size!==2||new Set(a.evidence_refs.map(x=>x.evidence_id)).size!==2)throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT");}
  if([...v.assumptions,...v.exclusions,...v.dependencies].some(x=>!text(x))||v.ai_task_refs.some(x=>!id(x)))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT"); }
function parseCreated(v:unknown,p:string,r:string,response:Response):CreatedRequirementVersion { const keys=["requirement_version_id","requirement_id","project_id","version_no","state","content_fingerprint","supersedes_version_ref","created_by","created_at","requirement_etag"] as const;
  if(!record(v)||!exact(v,keys)||!id(v.requirement_version_id)||v.requirement_id!==r||v.project_id!==p||!integer(v.version_no,1)||v.state!=="DRAFT"||typeof v.content_fingerprint!=="string"||!digest.test(v.content_fingerprint)||v.supersedes_version_ref!==null&&!id(v.supersedes_version_ref)||!id(v.created_by)||!instant(v.created_at)||typeof v.requirement_etag!=="string"||!etag.test(v.requirement_etag)||response.headers.get("etag")!==v.requirement_etag||response.headers.get("location")!==`/api/v1/projects/${p}/requirements/${r}/versions/${v.requirement_version_id}`)throw new RequirementVersionWriteError("REQUIREMENT_WRITE_UNAVAILABLE"); return Object.freeze(v) as unknown as CreatedRequirementVersion; }

export class RequirementVersionWriteClient { constructor(private readonly session:SessionClient){if(!(session instanceof SessionClient))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT");}
  async #send(p:string,r:string,v:string|null,op:"create"|"validate"|"submit-review",body:string|null,rootEtag:string|null,key:string){let response:Response;try{response=await this.session.writeProjectRequirementVersion(p,r,v,op,body,rootEtag,key);}catch(e){if(e instanceof SessionClientError&&(e.code==="AUTH_RELOGIN_REQUIRED"||e.code==="AUTH_CLIENT_BUSY"))throw new RequirementVersionWriteError(e.code);throw new RequirementVersionWriteError("REQUIREMENT_WRITE_UNAVAILABLE");}const raw=await payload(response);if(!response.ok)failure(response.status,raw);return{response,data:envelope(raw)};}
  async create(p:string,r:string,rootEtag:string,input:RequirementVersionCreateInput,key:string){ids(p,r);if(!etag.test(rootEtag)||!/^[\x20-\x7e]{16,128}$/.test(key))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT");createInput(input);const{response,data}=await this.#send(p,r,null,"create",JSON.stringify(input),rootEtag,key);if(response.status!==201)throw new RequirementVersionWriteError("REQUIREMENT_WRITE_UNAVAILABLE");return parseCreated(data,p,r,response);}
  async validate(p:string,r:string,v:string,key:string):Promise<RequirementValidationReport>{ids(p,r,v);if(!/^[\x20-\x7e]{16,128}$/.test(key))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT");const{response,data}=await this.#send(p,r,v,"validate",null,null,key);const keys=["audit_event_id","requirement_id","requirement_version_id","project_id","version_no","state","classification","valid","blocking_issues","warnings","coverage_summary","checked_at"] as const;if(response.status!==200||!record(data)||!exact(data,keys)||!id(data.audit_event_id)||data.requirement_id!==r||data.requirement_version_id!==v||data.project_id!==p||!integer(data.version_no,1)||data.state!=="DRAFT"||!(["STANDARD_FUNCTION","NONSTANDARD_FUNCTION","DIFFERENCE","PENDING_CONFIRMATION"] as unknown[]).includes(data.classification)||typeof data.valid!=="boolean"||!Array.isArray(data.blocking_issues)||data.blocking_issues.some(x=>typeof x!=="string"||!issue.test(x))||!Array.isArray(data.warnings)||data.warnings.some(x=>typeof x!=="string"||!issue.test(x))||!record(data.coverage_summary)||!exact(data.coverage_summary,["sources","acceptance_criteria","capability_assessments","assumptions","exclusions","dependencies","evidence_refs"])||Object.values(data.coverage_summary).some(x=>!integer(x))||!instant(data.checked_at))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_UNAVAILABLE");return Object.freeze({...data,blocking_issues:Object.freeze(data.blocking_issues),warnings:Object.freeze(data.warnings),coverage_summary:Object.freeze(data.coverage_summary)}) as unknown as RequirementValidationReport;}
  async submitReview(p:string,r:string,v:string,reviewers:readonly string[],key:string):Promise<RequirementReviewSubmission>{ids(p,r,v,...reviewers);if(reviewers.length===0||new Set(reviewers).size!==reviewers.length||!/^[\x20-\x7e]{16,128}$/.test(key))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_INVALID_INPUT");const body=JSON.stringify({reviewer_ids:reviewers,policy_ref:"REQUIREMENT_ALL_V1",due_at:null,submission_note:null});const{response,data}=await this.#send(p,r,v,"submit-review",body,null,key);const keys=["review_id","review_round_id","subject_type","project_id","requirement_id","requirement_version_id","policy_ref","reviewer_ids","state","round_no","review_etag","submitted_by","submitted_at"] as const;if(response.status!==201||!record(data)||!exact(data,keys)||!id(data.review_id)||!id(data.review_round_id)||data.subject_type!=="REQ-03"||data.project_id!==p||data.requirement_id!==r||data.requirement_version_id!==v||data.policy_ref!=="REQUIREMENT_ALL_V1"||!Array.isArray(data.reviewer_ids)||data.reviewer_ids.length!==reviewers.length||data.reviewer_ids.some((x,i)=>x!==reviewers[i])||data.state!=="IN_REVIEW"||!integer(data.round_no,1)||typeof data.review_etag!=="string"||!etag.test(data.review_etag)||response.headers.get("etag")!==data.review_etag||!id(data.submitted_by)||!instant(data.submitted_at))throw new RequirementVersionWriteError("REQUIREMENT_WRITE_UNAVAILABLE");return Object.freeze({...data,reviewer_ids:Object.freeze(data.reviewer_ids)}) as unknown as RequirementReviewSubmission;}
}
