import { beforeEach, describe, expect, it, vi } from "vitest";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { RequirementVersionWriteClient, RequirementVersionWriteError, type RequirementVersionCreateInput } from "./requirementVersionWriteClient";
const project="01234567-89ab-4cde-8123-456789abcdef",requirement="11234567-89ab-4cde-8123-456789abcdef",version="21234567-89ab-4cde-8123-456789abcdef",actor="31234567-89ab-4cde-8123-456789abcdef",trace="41234567-89ab-4cde-8123-456789abcdef",evidence="51234567-89ab-4cde-8123-456789abcdef",review="61234567-89ab-4cde-8123-456789abcdef",round="71234567-89ab-4cde-8123-456789abcdef",now="2026-10-08T12:00:00Z",key="synthetic-key-0001";
const input:RequirementVersionCreateInput={initial:true,base_version_ref:null,title:"审批",statement:"形成审批记录",rationale:"已确认访谈",domain_name:"文档",priority:"HIGH",risk:"MEDIUM",classification:"STANDARD_FUNCTION",sources:[{source_type:"PROJECT_EVIDENCE",source_object_id:evidence,source_version_ref:null,evidence_refs:[evidence]}],acceptance_criteria:[{observable_result:"形成记录",verification_method:"测试",required_data:"档案",required_environment:"Windows 11",evidence_requirement:"审计证据"}],capability_assessments:[],assumptions:[],exclusions:[],dependencies:[],ai_task_refs:[],client_reason:"形成需求草稿"};
function env(data:unknown,status=200,headers:Record<string,string>={}){return new Response(JSON.stringify({data,trace_id:trace}),{status,headers:{"Content-Type":"application/json",...headers}})}
function login(){return env({user:{user_id:actor,username_display:"用户"},deployment_role:"NONE",password_change_required:false,authorized_projects:[{project_id:project,name:"项目",role:"PROJECT_MANAGER"}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)});}
async function api(...responses:Response[]){const fetcher=vi.fn().mockResolvedValueOnce(login());for(const r of responses)fetcher.mockResolvedValueOnce(r);const session=new SessionClient(fetcher as typeof fetch);await session.login("user","synthetic");return{writer:new RequirementVersionWriteClient(session),fetcher};}
const created={requirement_version_id:version,requirement_id:requirement,project_id:project,version_no:1,state:"DRAFT",content_fingerprint:"a".repeat(64),supersedes_version_ref:null,created_by:actor,created_at:now,requirement_etag:'"v1"'};
describe("RequirementVersionWriteClient",()=>{beforeEach(()=>vi.restoreAllMocks());
it("creates with the frozen body, root ETag and original idempotency key",async()=>{const location=`/api/v1/projects/${project}/requirements/${requirement}/versions/${version}`;const{writer,fetcher}=await api(env(created,201,{ETag:'"v1"',Location:location}));await expect(writer.create(project,requirement,'"v0"',input,key)).resolves.toMatchObject(created);expect(fetcher.mock.calls[1]).toEqual([`/api/v1/projects/${project}/requirements/${requirement}/versions`,expect.objectContaining({method:"POST",headers:expect.objectContaining({"If-Match":'"v0"',"Idempotency-Key":key,"X-CSRF-Token":"a".repeat(64)}),body:JSON.stringify(input)})]);});
it("validates with an empty body and strict coverage",async()=>{const report={audit_event_id:trace,requirement_id:requirement,requirement_version_id:version,project_id:project,version_no:1,state:"DRAFT",classification:"STANDARD_FUNCTION",valid:true,blocking_issues:[],warnings:[],coverage_summary:{sources:1,acceptance_criteria:1,capability_assessments:0,assumptions:0,exclusions:0,dependencies:0,evidence_refs:1},checked_at:now};const{writer,fetcher}=await api(env(report));await expect(writer.validate(project,requirement,version,key)).resolves.toMatchObject({valid:true});expect(fetcher.mock.calls[1][0]).toContain(`${version}:validate`);expect(fetcher.mock.calls[1][1]).not.toHaveProperty("body");});
it("submits only the frozen policy and exact reviewer list",async()=>{const data={review_id:review,review_round_id:round,subject_type:"REQ-03",project_id:project,requirement_id:requirement,requirement_version_id:version,policy_ref:"REQUIREMENT_ALL_V1",reviewer_ids:[actor],state:"IN_REVIEW",round_no:1,review_etag:'"v1"',submitted_by:actor,submitted_at:now};const{writer,fetcher}=await api(env(data,201,{ETag:'"v1"'}));await expect(writer.submitReview(project,requirement,version,[actor],key)).resolves.toMatchObject(data);expect(JSON.parse(fetcher.mock.calls[1][1].body)).toEqual({reviewer_ids:[actor],policy_ref:"REQUIREMENT_ALL_V1",due_at:null,submission_note:null});});
it("rejects malformed structured input before transport and treats malformed success as uncertain",async()=>{const{writer,fetcher}=await api(env({...created,project_id:actor},201,{ETag:'"v1"',Location:`/api/v1/projects/${project}/requirements/${requirement}/versions/${version}`}));await expect(writer.create(project,requirement,'"v0"',{...input,acceptance_criteria:[{...input.acceptance_criteria[0]!,observable_result:" "}]},key)).rejects.toMatchObject({code:"REQUIREMENT_WRITE_INVALID_INPUT"});expect(fetcher).toHaveBeenCalledTimes(1);await expect(writer.create(project,requirement,'"v0"',input,key)).rejects.toBeInstanceOf(RequirementVersionWriteError);});
});
