"""Egress preview root and immutable source references.

Revision ID: 20261003_0068
Revises: 20261002_0067
"""
from __future__ import annotations
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

revision="20261003_0068"; down_revision="20261002_0067"; branch_labels=None; depends_on=None

def upgrade():
    ident=postgresql.UUID(as_uuid=True); ts=postgresql.TIMESTAMP(timezone=True,precision=6)
    op.create_table("ai_egress_previews",
        sa.Column("egress_preview_id",ident,primary_key=True,server_default=sa.text("uuidv7()")),sa.Column("scope",sa.Text(),nullable=False),sa.Column("project_id",ident),sa.Column("purpose_ref",sa.Text(),nullable=False),sa.Column("operation_type",sa.Text(),nullable=False),sa.Column("ai_provider_id",ident,nullable=False),sa.Column("provider_config_version_id",ident,nullable=False),sa.Column("ai_model_id",ident,nullable=False),sa.Column("data_region",sa.Text(),nullable=False),sa.Column("allowed_data_categories",postgresql.JSONB(),nullable=False),sa.Column("minimal_payload_policy_ref",sa.Text(),nullable=False),sa.Column("estimated_record_count",sa.BigInteger(),nullable=False),sa.Column("max_payload_bytes",sa.BigInteger(),nullable=False),sa.Column("max_input_tokens",sa.Integer(),nullable=False),sa.Column("max_retry_attempts",sa.Integer(),nullable=False),sa.Column("payload_fingerprint",sa.LargeBinary(),nullable=False),sa.Column("source_refs_fingerprint",sa.LargeBinary(),nullable=False),sa.Column("risk_codes",postgresql.JSONB(),nullable=False),sa.Column("created_by",ident,nullable=False),sa.Column("trace_id",ident,nullable=False),sa.Column("created_at",ts,nullable=False,server_default=sa.text("statement_timestamp()")),sa.Column("expires_at",ts,nullable=False),
        sa.ForeignKeyConstraint(["project_id"],["plm.prj_projects.project_id"],name="fk_ai_egress_previews__project"),sa.ForeignKeyConstraint(["created_by"],["plm.auth_users.user_id"],name="fk_ai_egress_previews__creator"),sa.ForeignKeyConstraint(["ai_model_id"],["plm.ai_models.ai_model_id"],name="fk_ai_egress_previews__model"),sa.ForeignKeyConstraint(["provider_config_version_id","ai_provider_id"],["plm.ai_provider_config_versions.provider_config_version_id","plm.ai_provider_config_versions.ai_provider_id"],name="fk_ai_egress_previews__provider_config"),
        sa.CheckConstraint("(scope='GLOBAL' AND project_id IS NULL) OR (scope='PROJECT' AND project_id IS NOT NULL)",name="ck_ai_egress_previews__scope"),sa.CheckConstraint("operation_type IN ('AI_TASK','RETRIEVAL_RUN','INDEX_BUILD','INDEX_REBUILD')",name="ck_ai_egress_previews__operation"),sa.CheckConstraint("purpose_ref ~ '^[A-Za-z][A-Za-z0-9._:/-]{0,127}$' AND minimal_payload_policy_ref ~ '^[A-Za-z][A-Za-z0-9._:/-]{0,127}$' AND data_region ~ '^[a-z][a-z0-9-]{0,63}$'",name="ck_ai_egress_previews__refs"),sa.CheckConstraint("jsonb_typeof(allowed_data_categories)='array' AND jsonb_array_length(allowed_data_categories) BETWEEN 1 AND 64 AND jsonb_typeof(risk_codes)='array' AND jsonb_array_length(risk_codes) BETWEEN 1 AND 32",name="ck_ai_egress_previews__arrays"),sa.CheckConstraint("egress_preview_id<>'00000000-0000-0000-0000-000000000000'::uuid AND ai_provider_id<>'00000000-0000-0000-0000-000000000000'::uuid AND provider_config_version_id<>'00000000-0000-0000-0000-000000000000'::uuid AND ai_model_id<>'00000000-0000-0000-0000-000000000000'::uuid AND created_by<>'00000000-0000-0000-0000-000000000000'::uuid AND trace_id<>'00000000-0000-0000-0000-000000000000'::uuid",name="ck_ai_egress_previews__uuid"),sa.CheckConstraint("estimated_record_count BETWEEN 0 AND 1000000000 AND max_payload_bytes BETWEEN 1 AND 1073741824 AND max_input_tokens BETWEEN 1 AND 1048576 AND max_retry_attempts BETWEEN 1 AND 10",name="ck_ai_egress_previews__bounds"),sa.CheckConstraint("octet_length(payload_fingerprint)=32 AND octet_length(source_refs_fingerprint)=32",name="ck_ai_egress_previews__fingerprints"),sa.CheckConstraint("created_at<expires_at AND isfinite(created_at) AND isfinite(expires_at)",name="ck_ai_egress_previews__time"),schema="plm")
    op.create_index("ix_ai_egress_previews__project_time","ai_egress_previews",["project_id",sa.text("created_at DESC"),sa.text("egress_preview_id DESC")],schema="plm")
    op.create_table("ai_egress_preview_source_refs",sa.Column("egress_preview_source_ref_id",ident,primary_key=True,server_default=sa.text("uuidv7()")),sa.Column("egress_preview_id",ident,nullable=False),sa.Column("ref_ordinal",sa.Integer(),nullable=False),sa.Column("resource_type",sa.Text(),nullable=False),sa.Column("owner_module",sa.Text(),nullable=False),sa.Column("object_type",sa.Text(),nullable=False),sa.Column("object_id",ident,nullable=False),sa.Column("version_id",ident,nullable=False),sa.Column("scope",sa.Text(),nullable=False),sa.Column("project_id",ident),sa.Column("added_at",ts,nullable=False,server_default=sa.text("statement_timestamp()")),sa.ForeignKeyConstraint(["egress_preview_id"],["plm.ai_egress_previews.egress_preview_id"],name="fk_ai_egress_preview_sources__preview"),sa.ForeignKeyConstraint(["project_id"],["plm.prj_projects.project_id"],name="fk_ai_egress_preview_sources__project"),sa.UniqueConstraint("egress_preview_id","ref_ordinal",name="uq_ai_egress_preview_sources__ordinal"),sa.UniqueConstraint("egress_preview_id","resource_type","owner_module","object_type","object_id","version_id",name="uq_ai_egress_preview_sources__semantic"),sa.CheckConstraint("ref_ordinal BETWEEN 1 AND 1000 AND resource_type ~ '^[A-Z][A-Z0-9-]{0,63}$' AND owner_module ~ '^[a-z][a-z0-9_]{0,63}$' AND object_type ~ '^[A-Z][A-Z0-9_]{0,63}$'",name="ck_ai_egress_preview_sources__shape"),sa.CheckConstraint("(scope='GLOBAL' AND project_id IS NULL) OR (scope='PROJECT' AND project_id IS NOT NULL)",name="ck_ai_egress_preview_sources__scope"),sa.CheckConstraint("egress_preview_source_ref_id<>'00000000-0000-0000-0000-000000000000'::uuid AND egress_preview_id<>'00000000-0000-0000-0000-000000000000'::uuid AND object_id<>'00000000-0000-0000-0000-000000000000'::uuid AND version_id<>'00000000-0000-0000-0000-000000000000'::uuid",name="ck_ai_egress_preview_sources__uuid"),schema="plm")
    op.create_index("ix_ai_egress_preview_sources__object","ai_egress_preview_source_refs",["owner_module","object_type","object_id","version_id"],schema="plm")
    op.execute(r"""CREATE FUNCTION plm.guard_ai_egress_preview() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE r text; e jsonb; mp uuid; ms text; BEGIN IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'AI egress preview history is immutable'; END IF; SELECT data_region INTO r FROM plm.ai_provider_config_versions WHERE provider_config_version_id=NEW.provider_config_version_id AND ai_provider_id=NEW.ai_provider_id; IF NOT FOUND OR r IS DISTINCT FROM NEW.data_region THEN RAISE EXCEPTION 'AI egress preview provider region mismatch'; END IF; SELECT ai_provider_id,model_state INTO mp,ms FROM plm.ai_models WHERE ai_model_id=NEW.ai_model_id FOR KEY SHARE; IF NOT FOUND OR mp IS DISTINCT FROM NEW.ai_provider_id OR ms<>'AVAILABLE' THEN RAISE EXCEPTION 'AI egress preview model mismatch'; END IF; FOR e IN SELECT value FROM jsonb_array_elements(NEW.allowed_data_categories||NEW.risk_codes) LOOP IF jsonb_typeof(e)<>'string' OR length(btrim(e#>>'{}'))=0 OR length(e#>>'{}')>64 THEN RAISE EXCEPTION 'AI egress preview array item invalid'; END IF; END LOOP; IF (SELECT count(*)<>count(DISTINCT value) FROM jsonb_array_elements(NEW.allowed_data_categories)) OR (SELECT count(*)<>count(DISTINCT value) FROM jsonb_array_elements(NEW.risk_codes)) THEN RAISE EXCEPTION 'AI egress preview array item duplicated'; END IF; RETURN NEW; END; $$; CREATE TRIGGER trg_ai_egress_preview_guard BEFORE INSERT OR UPDATE OR DELETE ON plm.ai_egress_previews FOR EACH ROW EXECUTE FUNCTION plm.guard_ai_egress_preview(); CREATE FUNCTION plm.guard_ai_egress_preview_source() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE s text; p uuid; BEGIN IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'AI egress preview source history is immutable'; END IF; SELECT scope,project_id INTO s,p FROM plm.ai_egress_previews WHERE egress_preview_id=NEW.egress_preview_id FOR KEY SHARE; IF NOT FOUND OR s IS DISTINCT FROM NEW.scope OR p IS DISTINCT FROM NEW.project_id THEN RAISE EXCEPTION 'AI egress preview source scope mismatch'; END IF; RETURN NEW; END; $$; CREATE TRIGGER trg_ai_egress_preview_source_guard BEFORE INSERT OR UPDATE OR DELETE ON plm.ai_egress_preview_source_refs FOR EACH ROW EXECUTE FUNCTION plm.guard_ai_egress_preview_source(); CREATE TRIGGER trg_ai_egress_preview_truncate BEFORE TRUNCATE ON plm.ai_egress_previews FOR EACH STATEMENT EXECUTE FUNCTION plm.guard_ai_task_truncate(); CREATE TRIGGER trg_ai_egress_preview_source_truncate BEFORE TRUNCATE ON plm.ai_egress_preview_source_refs FOR EACH STATEMENT EXECUTE FUNCTION plm.guard_ai_task_truncate();""")

def downgrade():
    if context.is_offline_mode(): raise RuntimeError("offline egress preview downgrade disabled")
    op.execute("LOCK TABLE plm.ai_egress_preview_source_refs,plm.ai_egress_previews IN ACCESS EXCLUSIVE MODE")
    op.execute("DO $$ BEGIN IF EXISTS(SELECT 1 FROM plm.ai_egress_previews) OR EXISTS(SELECT 1 FROM plm.ai_egress_preview_source_refs) THEN RAISE EXCEPTION 'AI egress preview history prevents downgrade'; END IF; END $$;")
    for t,n in (("ai_egress_preview_source_refs","trg_ai_egress_preview_source_truncate"),("ai_egress_previews","trg_ai_egress_preview_truncate"),("ai_egress_preview_source_refs","trg_ai_egress_preview_source_guard"),("ai_egress_previews","trg_ai_egress_preview_guard")): op.execute(f"DROP TRIGGER {n} ON plm.{t}")
    op.execute("DROP FUNCTION plm.guard_ai_egress_preview_source()");op.execute("DROP FUNCTION plm.guard_ai_egress_preview()")
    op.drop_index("ix_ai_egress_preview_sources__object",table_name="ai_egress_preview_source_refs",schema="plm");op.drop_table("ai_egress_preview_source_refs",schema="plm");op.drop_index("ix_ai_egress_previews__project_time",table_name="ai_egress_previews",schema="plm");op.drop_table("ai_egress_previews",schema="plm")
