import { flushPromises, mount } from "@vue/test-utils"; import { createMemoryHistory } from "vue-router";
import { afterEach, describe, expect, it, vi } from "vitest"; import { createAppRouter } from "@/app/router";
import { SessionClient } from "@/modules/auth/api/sessionClient"; import { EvidenceViewerClient } from "@/modules/evidence/api/evidenceViewerClient";
import { HandoverActionReadClient, type HandoverActionDetail, type HandoverActionSummary } from "@/modules/handover/api/handoverActionReadClient";
import ProjectHandoverActionView from "./ProjectHandoverActionView.vue";
const project="01234567-89ab-4cde-8123-456789abcdef", action="11234567-89ab-4cde-8123-456789abcdef", actor="21234567-89ab-4cde-8123-456789abcdef";
const doc="31234567-89ab-4cde-8123-456789abcdef", ver="41234567-89ab-4cde-8123-456789abcdef", ev="51234567-89ab-4cde-8123-456789abcdef", trace="61234567-89ab-4cde-8123-456789abcdef";
const now="2026-10-05T12:00:00Z"; const summary: HandoverActionSummary={action_item_id:action,source_kind:"ANALYSIS_ITEM",action_type:"CONFIRM_DECISION",title:"确认部署范围",owner_ref:actor,due_at:"2026-10-10T12:00:00Z",priority:"HIGH",action_state:"SUBMITTED",submitted_at:now,verified_at:null,closed_at:null,resolution_trace_ref:null,updated_at:now,etag:'"v2"'};
const detail: HandoverActionDetail={...summary,source_analysis_version_ref:ver,source_item_id:actor,human_source_reason:null,requested_input_spec:{fields:[{name:"部署范围",format:"文本",example:"总部与工厂",required:true}]},responses:[{document_id:doc,document_version_id:ver,ordinal:0}],evidence:[{evidence_id:ev,purpose:"SUBMISSION",ordinal:0}],created_by:actor,created_reason:"承接待确认项",created_at:now,verified_by:null,current_event:{action_state_event_id:trace,sequence_no:2,from_state:"IN_PROGRESS",to_state:"SUBMITTED",actor_id:actor,reason:"已提交资料",occurred_at:now}};
function response(data:unknown){return new Response(JSON.stringify({data,trace_id:trace}),{headers:{"Content-Type":"application/json"}})}
async function session(restricted=false){const api=new SessionClient(vi.fn().mockResolvedValue(response({user:{user_id:actor,username_display:"合成用户"},deployment_role:"NONE",password_change_required:restricted,authorized_projects:restricted?[]:[{project_id:project,name:"项目",role:"PROJECT_MANAGER"}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)})) as typeof fetch);await api.login("u","synthetic");return api}
function clients(){const actions=new HandoverActionReadClient(vi.fn() as typeof fetch),evidence=new EvidenceViewerClient(vi.fn() as typeof fetch);vi.spyOn(actions,"list").mockResolvedValue({items:[summary],next_cursor:null,has_more:false});vi.spyOn(actions,"get").mockResolvedValue(detail);vi.spyOn(evidence,"get").mockResolvedValue({evidence_id:ev,document_id:doc,document_version_id:ver,document_version_no:2,detected_mime:"application/pdf",size_bytes:10,locator:Object.freeze({locator_type:"DOCUMENT"}),precision:"DOCUMENT",display_label:"整个固定文档版本",short_preview:null,content_url:`/api/v1/projects/${project}/documents/${doc}/versions/${ver}/content`});return{actions,evidence}}
async function view(auth:SessionClient,supplied=clients()){const router=createAppRouter(createMemoryHistory());await router.push(`/projects/${project}/handover-actions`);await router.isReady();const wrapper=mount(ProjectHandoverActionView,{props:{session:auth,...supplied},global:{plugins:[router]}});await flushPromises();return{wrapper,...supplied}}
describe("ProjectHandoverActionView",()=>{afterEach(()=>vi.restoreAllMocks());
it("keeps reads closed without usable identity",async()=>{const supplied=clients();const absent=await view(new SessionClient(vi.fn() as typeof fetch),supplied);expect(absent.wrapper.text()).toContain("尚未读取");expect(supplied.actions.list).not.toHaveBeenCalled();absent.wrapper.unmount();const restricted=await view(await session(true),supplied);expect(restricted.wrapper.text()).toContain("须先修改密码");restricted.wrapper.unmount()});
it("shows SUBMITTED as pending verification and explicit maintenance guidance",async()=>{const result=await view(await session());expect(result.wrapper.text()).toContain("已提交不等于已完成");expect(result.wrapper.text()).toContain("已提交待验证");await result.wrapper.findAll("button").find(b=>b.text()==="查看待办详情")!.trigger("click");await flushPromises();expect(result.wrapper.text()).toContain("尚未验证和关闭");expect(result.wrapper.text()).toContain("部署范围 · 必填 · 文本 · 示例：总部与工厂");expect(result.wrapper.find("form").exists()).toBe(false);result.wrapper.unmount()});
it("locates submission Evidence only after user action",async()=>{const result=await view(await session());await result.wrapper.findAll("button").find(b=>b.text()==="查看待办详情")!.trigger("click");await flushPromises();expect(result.evidence.get).not.toHaveBeenCalled();await result.wrapper.findAll("button").find(b=>b.text().includes("定位SUBMISSION依据"))!.trigger("click");await flushPromises();expect(result.evidence.get).toHaveBeenCalledWith({kind:"PROJECT",projectId:project},ev);expect(result.wrapper.text()).toContain("整个固定文档版本");result.wrapper.unmount()});
});
