import { flushPromises, mount } from "@vue/test-utils";
import { createMemoryHistory } from "vue-router";
import { describe, expect, it, vi } from "vitest";
import { createAppRouter } from "@/app/router";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { SurveyReadClient } from "@/modules/survey/api/surveyReadClient";
import { SurveyRoundReadClient } from "@/modules/survey/api/surveyRoundClient";
import { ProjectDepartmentReadClient } from "@/modules/project/api/projectDepartmentReadClient";
import { ProjectMemberReadClient } from "@/modules/project/api/projectMemberReadClient";
import { EvidenceListClient } from "@/modules/evidence/api/evidenceListClient";
import { EvidenceViewerClient } from "@/modules/evidence/api/evidenceViewerClient";
import { HandoverActionReadClient } from "@/modules/handover/api/handoverActionReadClient";
import { SurveyConclusionReadClient, SurveyConclusionWriteClient, type SurveyConclusionView } from "@/modules/survey/api/surveyConclusionClient";
import ProjectSurveyConclusionView from "./ProjectSurveyConclusionView.vue";

const actor="01234567-89ab-4cde-8123-456789abcdef",project="11234567-89ab-4cde-8123-456789abcdef";
const survey="21234567-89ab-4cde-8123-456789abcdef",round="31234567-89ab-4cde-8123-456789abcdef";
const conclusion="41234567-89ab-4cde-8123-456789abcdef",series="51234567-89ab-4cde-8123-456789abcdef";
const department="61234567-89ab-4cde-8123-456789abcdef",responseId="71234567-89ab-4cde-8123-456789abcdef";
const evidence="81234567-89ab-4cde-8123-456789abcdef",documentId="91234567-89ab-4cde-8123-456789abcdef";
const documentVersion="a1234567-89ab-4cde-8123-456789abcdef",action="b1234567-89ab-4cde-8123-456789abcdef",now="2026-10-07T12:00:00Z";
function json(data:unknown){return new Response(JSON.stringify({data,trace_id:actor}),{headers:{"Content-Type":"application/json"}})}
async function session(){const api=new SessionClient(vi.fn().mockResolvedValue(json({user:{user_id:actor,username_display:"项目经理"},deployment_role:"NONE",password_change_required:false,authorized_projects:[{project_id:project,name:"项目",role:"PROJECT_MANAGER"}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)})) as typeof fetch);await api.login("manager","synthetic");return api}
function detail():SurveyConclusionView{return{survey_conclusion_id:conclusion,conclusion_series_id:series,project_id:project,survey_id:survey,round_refs:[round],ai_task_refs:[],version_no:1,state:"DRAFT",content_fingerprint:"a".repeat(64),department_count:1,module_count:1,evidence_count:1,open_issue_count:1,supersedes_ref:null,review_id:null,review_round_id:null,created_by:actor,created_at:now,department_conclusions:[{department_id:department,title:"业务范围",statement:"以现场记录为准。",response_refs:[responseId],ordinal:0}],module_conclusions:[{module_key:"BOM",title:"BOM结论",statement:"采用标准能力。",response_refs:[responseId],ordinal:0}],evidence_refs:[{reference_role:"SUPPORT",document_id:documentId,document_version_id:documentVersion,evidence_id:evidence,observed_evidence_lock_version:0,content_fingerprint:"b".repeat(64),ordinal:0}],open_issue_refs:[{issue_owner_module:"handover",issue_object_type:"HND-03",issue_id:action,observed_issue_state:"OPEN",observed_lock_version:0,is_blocking:true,ordinal:0}]}}
async function setup(){const auth=await session(),reads=new SurveyConclusionReadClient(vi.fn() as typeof fetch),writes=new SurveyConclusionWriteClient(auth),surveys=new SurveyReadClient(vi.fn() as typeof fetch),rounds=new SurveyRoundReadClient(vi.fn() as typeof fetch),departments=new ProjectDepartmentReadClient(vi.fn() as typeof fetch),members=new ProjectMemberReadClient(vi.fn() as typeof fetch),evidenceList=new EvidenceListClient(vi.fn() as typeof fetch),evidenceViewer=new EvidenceViewerClient(vi.fn() as typeof fetch),actions=new HandoverActionReadClient(vi.fn() as typeof fetch);const value=detail();vi.spyOn(reads,"list").mockResolvedValue({items:[value],next_cursor:null,has_more:false});vi.spyOn(reads,"get").mockResolvedValue(value);vi.spyOn(surveys,"listSurveys").mockResolvedValue({items:[{survey_id:survey,project_id:project,name:"现场调研",state:"ACTIVE",current_approved_version_ref:null,created_by:actor,created_at:now,updated_by:null,updated_at:now,etag:'"v0"'}],next_cursor:null,has_more:false});vi.spyOn(rounds,"list").mockResolvedValue({items:[],next_cursor:null,has_more:false});vi.spyOn(departments,"list").mockResolvedValue({items:[{department_id:department,code:"RD",name:"研发部",state:"ACTIVE",created_at:now,etag:'"v0"'}],next_cursor:null,has_more:false});vi.spyOn(members,"list").mockResolvedValue({items:[],next_cursor:null,has_more:false});vi.spyOn(evidenceList,"list").mockResolvedValue({items:[],next_cursor:null,has_more:false});vi.spyOn(actions,"list").mockResolvedValue({items:[],next_cursor:null,has_more:false});vi.spyOn(evidenceViewer,"get").mockResolvedValue({evidence_id:evidence,document_id:documentId,document_version_id:documentVersion,document_version_no:1,detected_mime:"application/pdf",size_bytes:100,locator:{locator_type:"PAGE",page_no:3},precision:"PARSED_NODE",display_label:"调研记录第3页",short_preview:"客户确认采用标准 BOM。",content_url:`/api/v1/projects/${project}/documents/${documentId}/versions/${documentVersion}/content`});const router=createAppRouter(createMemoryHistory());await router.push(`/projects/${project}/survey-conclusions`);await router.isReady();const wrapper=mount(ProjectSurveyConclusionView,{props:{session:auth,reads,writes,surveys,rounds,departments,members,evidenceList,evidenceViewer,actions},global:{plugins:[router]}});await flushPromises();return{wrapper,writes,evidenceViewer}}
function button(wrapper:ReturnType<typeof mount>,text:string){return wrapper.findAll("button").find(x=>x.text().includes(text))!}

describe("ProjectSurveyConclusionView",()=>{
  it("states the fact boundary and exposes click-through source locations",async()=>{const{wrapper,evidenceViewer}=await setup();expect(wrapper.text()).toContain("实际调研记录优先");expect(wrapper.text()).toContain("不能把 AI 建议当成客户事实");await button(wrapper,"查看结论").trigger("click");await flushPromises();expect(wrapper.text()).toContain("以现场记录为准");const issueLink=wrapper.findAll("a").find(x=>x.text().includes("打开待办并定位"))!;expect(issueLink.attributes("href")).toContain(`actionId=${action}`);await button(wrapper,"定位原文").trigger("click");await flushPromises();expect(evidenceViewer.get).toHaveBeenCalledWith({kind:"PROJECT",projectId:project},evidence);expect(wrapper.text()).toContain("调研记录第3页");expect(wrapper.text()).toContain("打开受权原文")});
  it("keeps the server validation report visible because validation does not change state",async()=>{const{wrapper,writes}=await setup();vi.spyOn(writes,"validate").mockResolvedValue({audit_event_id:evidence,survey_conclusion_id:conclusion,conclusion_series_id:series,project_id:project,survey_id:survey,version_no:1,state:"DRAFT",valid:true,blocking_issues:[],warnings:[],coverage_summary:{department_count:1,module_count:1,evidence_count:1,open_issue_count:1,response_count:1,support_evidence_count:1,conflict_evidence_count:0,current_open_blocking_issue_count:0},checked_at:now});await button(wrapper,"查看结论").trigger("click");await flushPromises();await button(wrapper,"验证当前来源").trigger("click");await flushPromises();expect(wrapper.text()).toContain("验证通过，可提交评审");expect(wrapper.text()).toContain("验证不会修改结论状态");expect(writes.validate).toHaveBeenCalledTimes(1)});
});
