<script setup lang="ts">
import { computed, inject, onUnmounted, reactive, ref, toRaw, watch } from "vue";
import { RouterLink, useRoute } from "vue-router";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { sessionClientKey } from "@/modules/auth/api/sessionContext";
import { SurveyReadClient, type SurveyView, type SurveyVersionView } from "@/modules/survey/api/surveyReadClient";
import { SurveyRoundReadClient, type SurveyRoundView } from "@/modules/survey/api/surveyRoundClient";
import { SurveyAssignmentReadClient } from "@/modules/survey/api/surveyAssignmentClient";
import { SurveyConclusionError, SurveyConclusionReadClient, SurveyConclusionWriteClient,
  type SurveyConclusionCreateInput, type SurveyConclusionCursor, type SurveyConclusionSummary,
  type SurveyConclusionValidation, type SurveyConclusionView } from "@/modules/survey/api/surveyConclusionClient";
import { ProjectDepartmentReadClient, type ProjectDepartmentView } from "@/modules/project/api/projectDepartmentReadClient";
import { ProjectMemberReadClient, type ProjectMemberView } from "@/modules/project/api/projectMemberReadClient";
import { EvidenceListClient, type EvidenceSummary } from "@/modules/evidence/api/evidenceListClient";
import { EvidenceViewerClient, EvidenceViewerClientError, type EvidenceViewerDescriptor } from "@/modules/evidence/api/evidenceViewerClient";
import { HandoverActionReadClient, type HandoverActionSummary } from "@/modules/handover/api/handoverActionReadClient";

const props=defineProps<{session?:SessionClient;reads?:SurveyConclusionReadClient;writes?:SurveyConclusionWriteClient;
  surveys?:SurveyReadClient;rounds?:SurveyRoundReadClient;assignments?:SurveyAssignmentReadClient;
  departments?:ProjectDepartmentReadClient;members?:ProjectMemberReadClient;evidenceList?:EvidenceListClient;
  evidenceViewer?:EvidenceViewerClient;actions?:HandoverActionReadClient}>();
const session=toRaw(props.session??inject(sessionClientKey,null)??new SessionClient()),identity=session.view,route=useRoute();
const reads=toRaw(props.reads??new SurveyConclusionReadClient()),writes=toRaw(props.writes??new SurveyConclusionWriteClient(session));
const surveyApi=toRaw(props.surveys??new SurveyReadClient()),roundApi=toRaw(props.rounds??new SurveyRoundReadClient());
const assignmentApi=toRaw(props.assignments??new SurveyAssignmentReadClient()),departmentApi=toRaw(props.departments??new ProjectDepartmentReadClient());
const memberApi=toRaw(props.members??new ProjectMemberReadClient()),evidenceListApi=toRaw(props.evidenceList??new EvidenceListClient());
const evidenceViewer=toRaw(props.evidenceViewer??new EvidenceViewerClient()),actionApi=toRaw(props.actions??new HandoverActionReadClient());
const projectId=computed(()=>typeof route.params.projectId==="string"?route.params.projectId:"");
const role=computed(()=>identity?.authorized_projects.find(x=>x.project_id===projectId.value)?.role??null);
const canManage=computed(()=>role.value==="PROJECT_MANAGER"||role.value==="IMPLEMENTATION_MEMBER");
const items=ref<readonly SurveyConclusionSummary[]>([]),cursor=ref<SurveyConclusionCursor|null>(null),detail=ref<SurveyConclusionView|null>(null);
const surveys=ref<readonly SurveyView[]>([]),rounds=ref<readonly SurveyRoundView[]>([]),departments=ref<readonly ProjectDepartmentView[]>([]);
const members=ref<readonly ProjectMemberView[]>([]),evidence=ref<readonly EvidenceSummary[]>([]),actions=ref<readonly HandoverActionSummary[]>([]);
const loaded=ref(false),busy=ref(false),detailBusy=ref(false),mutationBusy=ref(false),sourceBusy=ref(false),error=ref(""),detailError=ref(""),mutationError=ref(""),message=ref("");
const createOpen=ref(false),reviewOpen=ref(false),selectedRounds=ref<string[]>([]),reviewers=ref<string[]>([]),supersedes=ref("");
const validation=ref<SurveyConclusionValidation|null>(null),located=ref<EvidenceViewerDescriptor|null>(null),locationBusy=ref(false),locationError=ref("");
type ResponseChoice={id:string;departmentId:string;label:string}; const responses=ref<readonly ResponseChoice[]>([]);
type DepartmentDraft={departmentId:string;title:string;statement:string;responseRefs:string[]};
type ModuleDraft={moduleKey:string;title:string;statement:string;responseRefs:string[]};
const departmentDrafts=ref<DepartmentDraft[]>([]),moduleDrafts=ref<ModuleDraft[]>([]);
const evidenceRoles=reactive<Record<string,""|"SUPPORT"|"CONFLICT">>({}),issueSelections=reactive<Record<string,boolean>>({}),issueBlocking=reactive<Record<string,boolean>>({});
type Pending={kind:"create"|"validate"|"submit-review";conclusionId:string|null;key:string;body:SurveyConclusionCreateInput|readonly string[]|null};
const pending=ref<Pending|null>(null); let mounted=true,generation=0,locationGeneration=0;
const stateLabels:Record<string,string>={DRAFT:"草稿",IN_REVIEW:"评审中",APPROVED:"已批准",RETURNED:"已退回",SUPERSEDED:"已被替代",RESTRICTED:"受限"};
const closedRounds=computed(()=>rounds.value.filter(x=>x.state==="CLOSED"));
const selectedRoundObjects=computed(()=>selectedRounds.value.map(id=>rounds.value.find(x=>x.survey_round_id===id)).filter((x):x is SurveyRoundView=>!!x));
const selectedSurveyId=computed(()=>{const values=new Set(selectedRoundObjects.value.map(x=>x.survey_id));return values.size===1?[...values][0]!:""});
const surveyName=computed(()=>surveys.value.find(x=>x.survey_id===selectedSurveyId.value)?.name??selectedSurveyId.value);
const eligibleEvidence=computed(()=>evidence.value.filter(x=>x.eligibility_state==="ELIGIBLE"));
const eligibleReviewers=computed(()=>members.value.filter(x=>x.state==="ACTIVE"&&(x.role==="PROJECT_MANAGER"||x.role==="CUSTOMER_MANAGER")));
function key(kind:string){return `survey-conclusion-${kind}-${crypto.randomUUID()}`}
function resetCreate(){selectedRounds.value=[];responses.value=[];departmentDrafts.value=[];moduleDrafts.value=[];supersedes.value="";for(const k of Object.keys(evidenceRoles))delete evidenceRoles[k];for(const k of Object.keys(issueSelections))delete issueSelections[k];for(const k of Object.keys(issueBlocking))delete issueBlocking[k]}
function clearDetail(){detail.value=null;validation.value=null;reviewOpen.value=false;reviewers.value=[];located.value=null;locationError.value="";locationGeneration+=1}
async function load(next:SurveyConclusionCursor|null=null,replace=false){if(!mounted||!identity||identity.password_change_required||busy.value)return;const current=++generation;busy.value=true;error.value="";if(replace){items.value=[];cursor.value=null;loaded.value=false;clearDetail()}
  try{if(!loaded.value){const [s,r,d,m,e,a]=await Promise.all([surveyApi.listSurveys(projectId.value,200),roundApi.list(projectId.value,100),departmentApi.list(projectId.value),memberApi.list(projectId.value),evidenceListApi.list({kind:"PROJECT",projectId:projectId.value}),actionApi.list(projectId.value,200)]);if([s,r,d,m,e,a].some(x=>x.has_more))throw new Error("当前选择数据超过单页安全上限，请先缩小项目基础数据后再生成结论。");if(!mounted||current!==generation)return;surveys.value=s.items;rounds.value=r.items;departments.value=d.items;members.value=m.items;evidence.value=e.items;actions.value=a.items}
    const page=await reads.list(projectId.value,50,next);if(!mounted||current!==generation)return;const known=new Set(items.value.map(x=>x.survey_conclusion_id));if(page.items.some(x=>known.has(x.survey_conclusion_id)))throw new Error("结论列表发生重复，请刷新核对。");items.value=Object.freeze([...items.value,...page.items]);cursor.value=page.next_cursor;loaded.value=true}
  catch(e){if(mounted&&current===generation){error.value=e instanceof Error?e.message:"暂时无法读取调研结论。";if(replace){items.value=[];cursor.value=null;loaded.value=false}}}finally{if(mounted&&current===generation)busy.value=false}}
async function show(id:string){if(detailBusy.value||mutationBusy.value)return;const current=++generation;detailBusy.value=true;detailError.value="";clearDetail();try{const value=await reads.get(projectId.value,id);if(mounted&&current===generation)detail.value=value}catch(e){if(mounted&&current===generation)detailError.value=e instanceof Error?e.message:"暂时无法读取结论详情。"}finally{if(mounted&&current===generation)detailBusy.value=false}}
async function loadResponses(){if(!selectedRounds.value.length||!selectedSurveyId.value||sourceBusy.value){if(selectedRounds.value.length&& !selectedSurveyId.value)mutationError.value="所选轮次不属于同一调研定义，不能合并生成结论。";return}const current=++generation;sourceBusy.value=true;mutationError.value="";responses.value=[];try{const versions=new Map<string,SurveyVersionView>();const found:ResponseChoice[]=[];for(const round of selectedRoundObjects.value){const page=await assignmentApi.list(projectId.value,round.survey_round_id,200);if(page.has_more)throw new Error(`第 ${round.round_no} 轮分配超过单页安全上限，已停止生成。`);for(const assignment of page.items.filter(x=>x.state==="VALIDATED")){const full=await assignmentApi.get(projectId.value,round.survey_round_id,assignment.survey_assignment_id);let version=versions.get(full.survey_version_id);if(!version){version=await surveyApi.getVersion(projectId.value,full.survey_id,full.survey_version_id);versions.set(full.survey_version_id,version)}for(const answer of full.responses??[]){const question=version.questions.find(x=>x.question_id===answer.question_id);const department=departments.value.find(x=>x.department_id===full.department_id);found.push({id:answer.survey_response_id,departmentId:full.department_id,label:`第 ${round.round_no} 轮 · ${department?.name??"当前部门"} · ${question?.question_text??answer.question_id}`})}}}if(mounted&&current===generation)responses.value=Object.freeze(found)}catch(e){if(mounted&&current===generation)mutationError.value=e instanceof Error?e.message:"无法读取已确认答复。"}finally{if(mounted&&current===generation)sourceBusy.value=false}}
function addDepartment(){departmentDrafts.value.push({departmentId:"",title:"",statement:"",responseRefs:[]})} function addModule(){moduleDrafts.value.push({moduleKey:"",title:"",statement:"",responseRefs:[]})}
function removeDepartment(i:number){departmentDrafts.value.splice(i,1)} function removeModule(i:number){moduleDrafts.value.splice(i,1)}
function responseChoices(departmentId:string){return responses.value.filter(x=>x.departmentId===departmentId)}
async function execute(attempt:Pending){if(mutationBusy.value)return;const current=++generation;pending.value=attempt;mutationBusy.value=true;mutationError.value="";message.value="";try{if(attempt.kind==="create")await writes.create(projectId.value,attempt.body as SurveyConclusionCreateInput,attempt.key);else if(attempt.kind==="validate")validation.value=await writes.validate(projectId.value,attempt.conclusionId!,attempt.key);else await writes.submitReview(projectId.value,attempt.conclusionId!,attempt.body as readonly string[],attempt.key);if(!mounted||current!==generation)return;pending.value=null;message.value=attempt.kind==="validate"?"验证报告来自服务器当前来源快照；验证不会修改结论状态。":"操作已受理；以下事实来自服务器重新读取。";mutationBusy.value=false;if(attempt.kind==="create"){createOpen.value=false;resetCreate();await load(null,true)}else if(attempt.kind==="submit-review")await show(attempt.conclusionId!)}catch(e){if(!mounted||current!==generation)return;if(e instanceof SurveyConclusionError&&!e.uncertain){pending.value=null;mutationError.value=e.message}else mutationError.value="操作结果无法确认。已保留原操作号和正文；请先重新读取，或按原操作重试。";if(attempt.kind!=="validate")clearDetail()}finally{if(mounted&&current===generation)mutationBusy.value=false}}
function createConclusion(){if(!canManage.value||!selectedSurveyId.value||departmentDrafts.value.length<1||moduleDrafts.value.length<1)return;const body:SurveyConclusionCreateInput={survey_id:selectedSurveyId.value,round_refs:[...selectedRounds.value],department_conclusions:departmentDrafts.value.map(x=>({department_id:x.departmentId,title:x.title.trim(),statement:x.statement.trim(),response_refs:[...x.responseRefs]})),module_conclusions:moduleDrafts.value.map(x=>({module_key:x.moduleKey.trim(),title:x.title.trim(),statement:x.statement.trim(),response_refs:[...x.responseRefs]})),evidence_refs:eligibleEvidence.value.filter(x=>evidenceRoles[x.evidence_id]).map(x=>({evidence_id:x.evidence_id,reference_role:evidenceRoles[x.evidence_id] as "SUPPORT"|"CONFLICT"})),open_issue_refs:actions.value.filter(x=>issueSelections[x.action_item_id]).map(x=>({action_item_id:x.action_item_id,is_blocking:!!issueBlocking[x.action_item_id]})),ai_task_refs:[],supersedes_ref:supersedes.value||null};void execute({kind:"create",conclusionId:null,key:key("create"),body})}
function validateCurrent(){if(detail.value)void execute({kind:"validate",conclusionId:detail.value.survey_conclusion_id,key:key("validate"),body:null})}
function submitReview(){if(detail.value&&reviewers.value.length)void execute({kind:"submit-review",conclusionId:detail.value.survey_conclusion_id,key:key("review"),body:[...reviewers.value]})}
async function locate(evidenceId:string){if(!detail.value?.evidence_refs.some(x=>x.evidence_id===evidenceId)||locationBusy.value)return;const conclusionId=detail.value.survey_conclusion_id,current=++locationGeneration;locationBusy.value=true;located.value=null;locationError.value="";try{const value=await evidenceViewer.get({kind:"PROJECT",projectId:projectId.value},evidenceId);if(mounted&&current===locationGeneration&&detail.value?.survey_conclusion_id===conclusionId)located.value=value}catch(e){if(mounted&&current===locationGeneration)locationError.value=e instanceof EvidenceViewerClientError?e.message:"暂时无法定位原文。"}finally{if(mounted&&current===locationGeneration)locationBusy.value=false}}
watch(()=>route.params.projectId,()=>{generation+=1;items.value=[];cursor.value=null;loaded.value=false;surveys.value=[];rounds.value=[];departments.value=[];members.value=[];evidence.value=[];actions.value=[];busy.value=false;error.value="";mutationError.value="";message.value="";pending.value=null;createOpen.value=false;resetCreate();clearDetail();void load(null,true)},{immediate:true});
onUnmounted(()=>{mounted=false;generation+=1;locationGeneration+=1;pending.value=null});
</script>

<template><section class="conclusions" aria-labelledby="conclusion-title" :aria-busy="busy||detailBusy||mutationBusy||sourceBusy"><p class="section-kicker">项目调研</p><h1 id="conclusion-title">调研结论工作台</h1>
<p class="warning"><strong>实际调研记录优先。</strong> 模板和 AI 只能提供提示；结论必须由人工填写，并引用已确认答复与当前证据，不能把 AI 建议当成客户事实。</p>
<p><RouterLink :to="{name:'project-survey-rounds',params:{projectId}}">返回调研轮次</RouterLink> · <RouterLink :to="{name:'project-evidence',params:{projectId}}">管理项目证据</RouterLink> · <RouterLink :to="{name:'project-handover-actions',params:{projectId}}">管理待确认项</RouterLink></p>
<template v-if="!identity"><p role="status">尚未读取当前身份。请先登录。</p></template><template v-else-if="identity.password_change_required"><p role="status">当前账户须先修改密码，暂不能读取调研结论。</p></template><template v-else>
<div class="toolbar"><button :disabled="busy||mutationBusy" @click="load(null,true)">{{busy?'正在读取…':'刷新结论'}}</button><button v-if="canManage" :disabled="busy||mutationBusy" @click="createOpen=!createOpen">{{createOpen?'收起创建区':'生成调研结论'}}</button></div>
<p v-if="error" role="alert">{{error}}</p><p v-if="mutationError" role="alert">{{mutationError}}</p><p v-if="message" role="status">{{message}}</p><button v-if="pending" :disabled="mutationBusy" @click="execute(pending)">使用原操作号和正文重试</button>
<form v-if="createOpen&&canManage" @submit.prevent="createConclusion"><h2>生成一版人工结论</h2><p>以下带“人工维护”的字段必须由项目人员依据实际访谈填写；页面只提供已授权事实供选择。</p>
<fieldset><legend>1. 选择已关闭调研轮次（必选，且须属于同一调研）</legend><label v-for="item in closedRounds" :key="item.survey_round_id" class="check"><input v-model="selectedRounds" type="checkbox" :value="item.survey_round_id">第 {{item.round_no}} 轮 · {{surveys.find(x=>x.survey_id===item.survey_id)?.name??item.survey_id}}</label><p v-if="selectedRounds.length">当前调研：{{surveyName||'所选轮次不一致'}}</p><button type="button" :disabled="sourceBusy||!selectedSurveyId" @click="loadResponses">{{sourceBusy?'正在读取…':'加载所选轮次的已确认答复'}}</button></fieldset>
<fieldset><legend>2. 部门结论（至少一项，人工维护）</legend><div v-for="(draft,index) in departmentDrafts" :key="index" class="draft"><label>部门<select v-model="draft.departmentId" required><option value="">请选择</option><option v-for="d in departments.filter(x=>x.state==='ACTIVE')" :key="d.department_id" :value="d.department_id">{{d.name}}（{{d.code}}）</option></select></label><label>标题<input v-model.trim="draft.title" required maxlength="255" placeholder="概括该部门确认的业务结论"></label><label>结论正文<textarea v-model.trim="draft.statement" required maxlength="20000" placeholder="填写已与客户核对的实际调研结论"></textarea></label><fieldset><legend>引用该部门已确认答复</legend><label v-for="answer in responseChoices(draft.departmentId)" :key="answer.id" class="check"><input v-model="draft.responseRefs" type="checkbox" :value="answer.id">{{answer.label}}</label><p v-if="draft.departmentId&&!responseChoices(draft.departmentId).length">所选轮次没有该部门的 VALIDATED 答复。</p></fieldset><button type="button" @click="removeDepartment(index)">移除此部门结论</button></div><button type="button" @click="addDepartment">增加部门结论</button></fieldset>
<fieldset><legend>3. 模块结论（至少一项，人工维护）</legend><div v-for="(draft,index) in moduleDrafts" :key="index" class="draft"><label>模块标识<input v-model.trim="draft.moduleKey" required maxlength="128" placeholder="例如：BOM / Change / Document"></label><label>标题<input v-model.trim="draft.title" required maxlength="255"></label><label>结论正文<textarea v-model.trim="draft.statement" required maxlength="20000" placeholder="说明标准功能、差异或实施结论"></textarea></label><fieldset><legend>引用已确认答复</legend><label v-for="answer in responses" :key="answer.id" class="check"><input v-model="draft.responseRefs" type="checkbox" :value="answer.id">{{answer.label}}</label></fieldset><button type="button" @click="removeModule(index)">移除此模块结论</button></div><button type="button" @click="addModule">增加模块结论</button></fieldset>
<fieldset><legend>4. 当前证据与冲突（可选）</legend><p>只保存 Evidence 引用；不会把原文复制进表格。</p><label v-for="entry in eligibleEvidence" :key="entry.evidence_id">{{entry.display_label}}<select v-model="evidenceRoles[entry.evidence_id]"><option value="">不引用</option><option value="SUPPORT">支持结论</option><option value="CONFLICT">与结论冲突</option></select></label></fieldset>
<fieldset><legend>5. 未关闭待确认项（可选）</legend><label v-for="action in actions.filter(x=>!['CLOSED','CANCELLED'].includes(x.action_state))" :key="action.action_item_id" class="check"><input v-model="issueSelections[action.action_item_id]" type="checkbox">{{action.title}} · {{action.action_state}}</label><label v-for="action in actions.filter(x=>issueSelections[x.action_item_id])" :key="'b'+action.action_item_id" class="check"><input v-model="issueBlocking[action.action_item_id]" type="checkbox">“{{action.title}}”阻塞结论</label></fieldset>
<label>替代既有版本（可选）<select v-model="supersedes"><option value="">新结论系列</option><option v-for="item in items.filter(x=>x.survey_id===selectedSurveyId&&x.state!=='SUPERSEDED')" :key="item.survey_conclusion_id" :value="item.survey_conclusion_id">版本 {{item.version_no}} · {{new Date(item.created_at).toLocaleString('zh-CN')}}</option></select></label><button :disabled="mutationBusy||!selectedSurveyId||!responses.length||!departmentDrafts.length||!moduleDrafts.length">生成并重新读取</button></form>
<p v-if="loaded&&!items.length" role="status">当前项目还没有调研结论。</p><ol v-if="items.length" aria-label="调研结论"><li v-for="item in items" :key="item.survey_conclusion_id"><strong>{{surveys.find(x=>x.survey_id===item.survey_id)?.name??'调研结论'}} · 版本 {{item.version_no}}</strong><span>{{stateLabels[item.state]}} · 部门 {{item.department_count}} · 模块 {{item.module_count}} · 证据 {{item.evidence_count}} · 待确认 {{item.open_issue_count}}</span><button :disabled="detailBusy||mutationBusy" @click="show(item.survey_conclusion_id)">查看结论</button></li></ol><button v-if="cursor" :disabled="busy" @click="load(cursor)">加载更多</button>
<p v-if="detailBusy" role="status">正在读取结论详情…</p><p v-if="detailError" role="alert">{{detailError}}</p><article v-if="detail"><h2>结论版本 {{detail.version_no}} · {{stateLabels[detail.state]}}</h2><p>内容指纹：{{detail.content_fingerprint}}</p><section><h3>部门结论</h3><div v-for="entry in detail.department_conclusions" :key="entry.ordinal"><h4>{{departments.find(x=>x.department_id===entry.department_id)?.name??entry.title}}</h4><p><strong>{{entry.title}}</strong></p><p>{{entry.statement}}</p><small>固定答复 {{entry.response_refs.length}} 条</small></div></section><section><h3>模块结论</h3><div v-for="entry in detail.module_conclusions" :key="entry.ordinal"><h4>{{entry.module_key}} · {{entry.title}}</h4><p>{{entry.statement}}</p><small>固定答复 {{entry.response_refs.length}} 条</small></div></section>
<section><h3>证据定位</h3><p v-if="!detail.evidence_refs.length">未引用证据。</p><ul><li v-for="entry in detail.evidence_refs" :key="entry.evidence_id">{{entry.reference_role==='SUPPORT'?'支持':'冲突'}} · {{entry.evidence_id}} <button :disabled="locationBusy" @click="locate(entry.evidence_id)">定位原文</button></li></ul><p v-if="locationError" role="alert">{{locationError}}</p><div v-if="located" class="location"><strong>{{located.display_label}}</strong><p>{{located.short_preview??'该定位不提供预览，请打开受权原文。'}}</p><p>定位精度：{{located.precision}} · {{JSON.stringify(located.locator)}}</p><a :href="located.content_url" target="_blank" rel="noopener">打开受权原文</a></div></section>
<section><h3>待确认项定位</h3><p v-if="!detail.open_issue_refs.length">未引用待确认项。</p><ul><li v-for="entry in detail.open_issue_refs" :key="entry.issue_id"><span>{{entry.is_blocking?'阻塞':'非阻塞'}} · {{entry.observed_issue_state}}</span> <RouterLink :to="{name:'project-handover-actions',params:{projectId},query:{actionId:entry.issue_id}}">打开待办并定位</RouterLink></li></ul></section>
<div v-if="canManage&&['DRAFT','RETURNED'].includes(detail.state)" class="toolbar"><button :disabled="mutationBusy" @click="validateCurrent">验证当前来源</button><button :disabled="mutationBusy" @click="reviewOpen=!reviewOpen">提交正式评审</button></div><section v-if="validation"><h3>验证报告</h3><p :class="validation.valid?'pass':'warning'">{{validation.valid?'验证通过，可提交评审。':'仍有阻塞问题，不能据此认定通过。'}}</p><ul><li v-for="issue in validation.blocking_issues" :key="issue">{{issue}}</li></ul><p>答复 {{validation.coverage_summary.response_count}} · 支持证据 {{validation.coverage_summary.support_evidence_count}} · 当前阻塞待办 {{validation.coverage_summary.current_open_blocking_issue_count}}</p></section>
<form v-if="reviewOpen&&canManage&&['DRAFT','RETURNED'].includes(detail.state)" @submit.prevent="submitReview"><h3>选择正式评审人</h3><p>评审资格由服务器按当前成员、角色和固定策略再次核验。</p><label v-for="member in eligibleReviewers" :key="member.user.user_id" class="check"><input v-model="reviewers" type="checkbox" :value="member.user.user_id">{{member.user.display_name}} · {{member.role}}</label><button :disabled="mutationBusy||!reviewers.length">提交正式评审</button></form></article></template></section></template>

<style scoped>.conclusions{max-width:76rem;margin:1rem auto;padding:1.5rem;background:#fff;border-radius:1rem}.warning{padding:.8rem 1rem;background:#fff8e9;border-left:.3rem solid #d29b42}.pass{padding:.8rem 1rem;background:#edf8ef;border-left:.3rem solid #4b9b5e}.toolbar{display:flex;gap:.5rem;flex-wrap:wrap;margin:.7rem 0}.conclusions>ol{display:grid;gap:.7rem;padding:0;list-style:none}.conclusions>ol>li,.conclusions article,.conclusions form,.draft,.location{display:grid;gap:.65rem;padding:1rem;border:1px solid #cbd5df;border-radius:.7rem;margin-top:.8rem}.conclusions label{display:grid;gap:.25rem}.conclusions input,.conclusions textarea,.conclusions select{box-sizing:border-box;width:100%;padding:.5rem}.conclusions fieldset{display:grid;gap:.5rem}.conclusions .check{display:flex;align-items:start}.conclusions .check input{width:auto;margin:.2rem .5rem 0 0}.conclusions [role=alert]{color:#a21d25}.conclusions li{overflow-wrap:anywhere}</style>
