import { flushPromises, mount } from "@vue/test-utils";
import { createMemoryHistory } from "vue-router";
import { describe, expect, it, vi } from "vitest";
import { createAppRouter } from "@/app/router";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { ProjectDepartmentReadClient } from "@/modules/project/api/projectDepartmentReadClient";
import { ProjectMemberReadClient } from "@/modules/project/api/projectMemberReadClient";
import { EvidenceListClient } from "@/modules/evidence/api/evidenceListClient";
import { SurveyReadClient, type SurveyVersionView } from "@/modules/survey/api/surveyReadClient";
import { SurveyRoundReadClient, type SurveyRoundView } from "@/modules/survey/api/surveyRoundClient";
import { SurveyAssignmentReadClient, SurveyAssignmentWriteClient, type SurveyAssignmentView } from "@/modules/survey/api/surveyAssignmentClient";
import ProjectSurveyAssignmentView from "./ProjectSurveyAssignmentView.vue";

const actor="01234567-89ab-4cde-8123-456789abcdef",project="11234567-89ab-4cde-8123-456789abcdef",survey="21234567-89ab-4cde-8123-456789abcdef",version="31234567-89ab-4cde-8123-456789abcdef",roundId="41234567-89ab-4cde-8123-456789abcdef",assignmentId="51234567-89ab-4cde-8123-456789abcdef",department="61234567-89ab-4cde-8123-456789abcdef",question="71234567-89ab-4cde-8123-456789abcdef",evidenceId="81234567-89ab-4cde-8123-456789abcdef",now="2026-10-06T12:00:00Z";
const round:SurveyRoundView={survey_round_id:roundId,survey_id:survey,survey_version_id:version,project_id:project,round_no:1,state:"OPEN",scheduled_start_at:null,scheduled_end_at:null,location_note:null,opened_by:actor,opened_at:now,closed_by:null,closed_at:null,close_report_fingerprint:null,cancelled_by:null,cancelled_at:null,cancellation_reason:null,created_by:actor,created_at:now,updated_by:actor,updated_at:now,etag:'"v1"',source_record_count:0,source_records:[]};
const definition:SurveyVersionView={survey_version_id:version,survey_id:survey,project_id:project,version_no:1,state:"APPROVED",content_fingerprint:"a".repeat(64),declared_question_count:1,declared_option_count:0,declared_source_count:1,declared_target_department_count:1,supersedes_version_ref:null,review_ref:null,review_round_ref:null,created_by:actor,created_at:now,questions:[{question_id:question,sequence_no:0,topic:"现状",question_text:"当前流程是什么？",objective:"形成事实",answer_type:"TEXT",validation_rule:{},required:true,condition_rule:null,expected_output:"文字说明",evidence_required:false,options:[],sources:[{source_kind:"MANUAL",handover_item_row_id:null,handover_analysis_version_id:null,handover_analysis_id:null,capability_item_row_id:null,capability_baseline_version_id:null,capability_baseline_id:null,template_document_version_id:null,template_document_id:null,manual_source_note:"现场调研",ordinal:0}]}],target_departments:[{department_id:department,ordinal:0}]};
function assignment(state:SurveyAssignmentView["state"]="ASSIGNED",detail=false):SurveyAssignmentView{return{survey_assignment_id:assignmentId,survey_round_id:roundId,survey_id:survey,survey_version_id:version,project_id:project,department_id:department,assignee_user_id:actor,state,submitted_by:null,submitted_at:null,validated_by:null,validated_at:null,returned_by:null,returned_at:null,return_comment:null,created_by:actor,created_at:now,updated_by:null,updated_at:now,etag:'"v0"',response_count:0,...(detail?{responses:[]}:{})}}
async function auth(role="PROJECT_MANAGER"){const payload={data:{user:{user_id:actor,username_display:"项目经理"},deployment_role:"NONE",password_change_required:false,authorized_projects:[{project_id:project,name:"项目",role}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)},trace_id:actor};const client=new SessionClient(vi.fn().mockResolvedValue(new Response(JSON.stringify(payload),{status:200,headers:{"Content-Type":"application/json"}})) as typeof fetch);await client.login("manager","synthetic");return client}
async function mounted(session:SessionClient,state=assignment("ASSIGNED",true)){const rounds=new SurveyRoundReadClient(vi.fn() as typeof fetch),assignments=new SurveyAssignmentReadClient(vi.fn() as typeof fetch),writes=new SurveyAssignmentWriteClient(session),surveys=new SurveyReadClient(vi.fn() as typeof fetch),departments=new ProjectDepartmentReadClient(vi.fn() as typeof fetch),members=new ProjectMemberReadClient(vi.fn() as typeof fetch),evidence=new EvidenceListClient(vi.fn() as typeof fetch);vi.spyOn(rounds,"get").mockResolvedValue(round);vi.spyOn(surveys,"getVersion").mockResolvedValue(definition);vi.spyOn(departments,"list").mockResolvedValue({items:[{department_id:department,code:"DEMO",name:"研发部",state:"ACTIVE",created_at:now,etag:'"v0"'}],next_cursor:null,has_more:false});vi.spyOn(members,"list").mockResolvedValue({items:[{member_id:actor,user:{user_id:actor,display_name:"项目经理"},role:"PROJECT_MANAGER",department:{department_id:department,name:"研发部"},state:"ACTIVE",effective_at:now,ended_at:null,etag:'"v0"'}],next_cursor:null,has_more:false});vi.spyOn(evidence,"list").mockResolvedValue({items:[{evidence_id:evidenceId,document_id:survey,document_version_id:version,display_label:"访谈纪要",display_excerpt:"客户现场说明",eligibility_state:"ELIGIBLE",created_at:now}],next_cursor:null,has_more:false});vi.spyOn(assignments,"list").mockResolvedValue({items:[assignment()],next_cursor:null,has_more:false});vi.spyOn(assignments,"get").mockResolvedValue(state);const router=createAppRouter(createMemoryHistory());await router.push(`/projects/${project}/survey-rounds/${roundId}/assignments`);await router.isReady();const wrapper=mount(ProjectSurveyAssignmentView,{props:{session,rounds,assignments,writes,surveys,departments,members,evidence},global:{plugins:[router]}});await flushPromises();return{wrapper,assignments,writes}}
function button(wrapper:Awaited<ReturnType<typeof mounted>>["wrapper"],label:string){const found=wrapper.findAll("button").find(x=>x.text().includes(label));if(!found)throw new Error(`missing ${label}`);return found}

describe("ProjectSurveyAssignmentView",()=>{
 it("keeps all project reads closed without a usable identity",async()=>{const session=new SessionClient(vi.fn() as typeof fetch);const rounds=new SurveyRoundReadClient(vi.fn() as typeof fetch);const get=vi.spyOn(rounds,"get");const router=createAppRouter(createMemoryHistory());await router.push(`/projects/${project}/survey-rounds/${roundId}/assignments`);await router.isReady();const wrapper=mount(ProjectSurveyAssignmentView,{props:{session,rounds},global:{plugins:[router]}});await flushPromises();expect(wrapper.text()).toContain("尚未读取当前身份");expect(get).not.toHaveBeenCalled()});
 it("renders friendly target, evidence and explicit fact warning",async()=>{const{wrapper}=await mounted(await auth());expect(wrapper.text()).toContain("AI 建议和页面录入都不是客户确认事实");expect(wrapper.text()).toContain("研发部");await button(wrapper,"查看与填写").trigger("click");await flushPromises();expect(wrapper.text()).toContain("当前流程是什么");expect(wrapper.text()).toContain("访谈纪要");expect(wrapper.text()).not.toContain(department)});
 it("creates and records with server reread while retaining no invented PASS",async()=>{const{wrapper,assignments,writes}=await mounted(await auth());const create=vi.spyOn(writes,"create").mockResolvedValue(assignment());await button(wrapper,"新建分配").trigger("click");await wrapper.find("select").setValue(department);await wrapper.find("form").trigger("submit");await flushPromises();expect(create).toHaveBeenCalledWith(project,roundId,department,null,expect.stringContaining("survey-assignment-create-"));await button(wrapper,"查看与填写").trigger("click");await flushPromises();const record=vi.spyOn(writes,"record").mockResolvedValue({});const area=wrapper.findAll("textarea").find(x=>x.attributes("maxlength")==="20000");await area!.setValue("现有流程由邮件驱动");await wrapper.find("form").trigger("submit");await flushPromises();expect(record).toHaveBeenCalled();expect(assignments.list).toHaveBeenCalledTimes(3);expect(wrapper.text()).not.toContain("自动确认通过")});
});
