import { flushPromises, mount } from "@vue/test-utils";
import { createMemoryHistory } from "vue-router";
import { describe, expect, it, vi } from "vitest";
import { createAppRouter } from "@/app/router";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { SurveyRoundError, SurveyRoundReadClient, SurveyRoundWriteClient, type SurveyRoundView } from "@/modules/survey/api/surveyRoundClient";
import ProjectSurveyRoundView from "./ProjectSurveyRoundView.vue";

const actor="01234567-89ab-4cde-8123-456789abcdef",project="11234567-89ab-4cde-8123-456789abcdef",survey="21234567-89ab-4cde-8123-456789abcdef",version="31234567-89ab-4cde-8123-456789abcdef",round="41234567-89ab-4cde-8123-456789abcdef",now="2026-10-06T12:00:00Z";
function view(state:"PLANNED"|"OPEN"|"CLOSED"|"CANCELLED"="PLANNED",etag='"v0"'):SurveyRoundView{return{survey_round_id:round,survey_id:survey,survey_version_id:version,project_id:project,round_no:1,state,scheduled_start_at:null,scheduled_end_at:null,location_note:null,opened_by:state==="OPEN"||state==="CLOSED"?actor:null,opened_at:state==="OPEN"||state==="CLOSED"?now:null,closed_by:state==="CLOSED"?actor:null,closed_at:state==="CLOSED"?now:null,close_report_fingerprint:state==="CLOSED"?"a".repeat(64):null,cancelled_by:state==="CANCELLED"?actor:null,cancelled_at:state==="CANCELLED"?now:null,cancellation_reason:state==="CANCELLED"?"取消":null,created_by:actor,created_at:now,updated_by:actor,updated_at:now,etag,source_record_count:0,source_records:[]}}
function response(data:unknown){return new Response(JSON.stringify({data,trace_id:actor}),{headers:{"Content-Type":"application/json"}})}
async function session(role:"PROJECT_MANAGER"|"IMPLEMENTATION_MEMBER"="PROJECT_MANAGER",restricted=false){const fetcher=vi.fn().mockResolvedValue(response({user:{user_id:actor,username_display:"项目人员"},deployment_role:"NONE",password_change_required:restricted,authorized_projects:restricted?[]:[{project_id:project,name:"项目",role}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)}));const api=new SessionClient(fetcher as typeof fetch);await api.login("user","synthetic");return api}
async function mounted(auth:SessionClient,state:SurveyRoundView=view()){const reads=new SurveyRoundReadClient(vi.fn() as typeof fetch),writes=new SurveyRoundWriteClient(auth);vi.spyOn(reads,"list").mockResolvedValue({items:[state],next_cursor:null,has_more:false});vi.spyOn(reads,"get").mockResolvedValue(state);const router=createAppRouter(createMemoryHistory());await router.push(`/projects/${project}/survey-rounds`);await router.isReady();const wrapper=mount(ProjectSurveyRoundView,{props:{session:auth,rounds:reads,writes},global:{plugins:[router]}});await flushPromises();return{wrapper,reads,writes}}
function button(wrapper:ReturnType<typeof mount>,text:string){return wrapper.findAll("button").find(x=>x.text().includes(text))!}

describe("ProjectSurveyRoundView",()=>{
 it("keeps reads closed without usable identity",async()=>{const auth=new SessionClient(vi.fn() as typeof fetch);const reads=new SurveyRoundReadClient(vi.fn() as typeof fetch);const list=vi.spyOn(reads,"list");const router=createAppRouter(createMemoryHistory());await router.push(`/projects/${project}/survey-rounds`);await router.isReady();const wrapper=mount(ProjectSurveyRoundView,{props:{session:auth,rounds:reads,writes:{} as SurveyRoundWriteClient},global:{plugins:[router]}});await flushPromises();expect(wrapper.text()).toContain("尚未读取当前身份");expect(list).not.toHaveBeenCalled()});
 it("shows manager lifecycle controls and server-fact warnings",async()=>{const{wrapper}=await mounted(await session(),view("OPEN",'"v1"'));expect(wrapper.text()).toContain("PLANNED 和 OPEN 均不是客户确认事实");await button(wrapper,"查看与操作").trigger("click");await flushPromises();expect(wrapper.text()).toContain("验证并关闭");expect(wrapper.text()).not.toContain("开始轮次");expect(wrapper.text()).toContain("固定来源 0 条")});
 it("lets implementation members create and patch but not run manager transitions",async()=>{const{wrapper}=await mounted(await session("IMPLEMENTATION_MEMBER"));expect(wrapper.text()).toContain("新建计划轮次");await button(wrapper,"查看与操作").trigger("click");await flushPromises();expect(wrapper.text()).toContain("修改计划");expect(wrapper.text()).not.toContain("开始轮次")});
 it("creates once, then reports only the server re-read state",async()=>{const auth=await session(),planned=view();const{wrapper,reads,writes}=await mounted(auth,planned);const create=vi.spyOn(writes,"create").mockResolvedValue(planned);button(wrapper,"新建计划轮次").trigger("click");await flushPromises();const inputs=wrapper.findAll("input");await inputs[0]!.setValue(survey);await inputs[1]!.setValue(version);await wrapper.find("form").trigger("submit");await flushPromises();expect(create).toHaveBeenCalledTimes(1);expect(wrapper.text()).toContain("以下状态来自服务器重新读取");expect(reads.list).toHaveBeenCalledTimes(2);expect(reads.get).toHaveBeenCalledWith(project,round)});
 it("renders an incomplete CLOSE as a safe rejection",async()=>{const auth=await session(),open=view("OPEN",'"v1"');const{wrapper,writes}=await mounted(auth,open);vi.spyOn(writes,"close").mockRejectedValue(new SurveyRoundError("SURVEY_ROUND_INCOMPLETE"));await button(wrapper,"查看与操作").trigger("click");await flushPromises();await button(wrapper,"验证并关闭").trigger("click");await wrapper.find('input[type="checkbox"]').setValue(true);await wrapper.find("form").trigger("submit");await flushPromises();expect(wrapper.text()).toContain("尚未满足关闭条件");expect(wrapper.text()).not.toContain("操作已提交")});
});
