<script setup lang="ts">
import { computed, inject, onUnmounted, reactive, ref, toRaw, watch } from "vue";
import { RouterLink, useRoute } from "vue-router";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { sessionClientKey } from "@/modules/auth/api/sessionContext";
import { SurveyRoundError, SurveyRoundReadClient, SurveyRoundWriteClient, type SurveyRoundCursor,
  type SurveyRoundScheduleInput, type SurveyRoundView } from "@/modules/survey/api/surveyRoundClient";

const props=defineProps<{session?:SessionClient;rounds?:SurveyRoundReadClient;writes?:SurveyRoundWriteClient}>();
const session=toRaw(props.session??inject(sessionClientKey,null)??new SessionClient()); const rounds=toRaw(props.rounds??new SurveyRoundReadClient());
const writes=toRaw(props.writes??new SurveyRoundWriteClient(session)); const identity=session.view; const route=useRoute();
const items=ref<readonly SurveyRoundView[]>([]),cursor=ref<SurveyRoundCursor|null>(null),detail=ref<SurveyRoundView|null>(null);
const busy=ref(false),detailBusy=ref(false),mutationBusy=ref(false),loaded=ref(false),error=ref(""),detailError=ref(""),mutationError=ref(""),message=ref("");
const createOpen=ref(false),operation=ref<"patch"|"open"|"close"|"cancel"|null>(null),confirmed=ref(false);
const createForm=reactive({surveyId:"",versionId:"",start:"",end:"",location:""}); const editForm=reactive({start:"",end:"",location:"",reason:""});
type Pending={project:string;actor:string;roundId:string|null;operation:"create"|"open"|"close"|"cancel";etag:string|null;key:string;body:Record<string,unknown>|null};
const pending=ref<Pending|null>(null); let generation=0,mounted=true;
const projectId=computed(()=>typeof route.params.projectId==="string"?route.params.projectId:"");
const role=computed(()=>identity?.authorized_projects.find(x=>x.project_id===projectId.value)?.role??null);
const canCreate=computed(()=>role.value==="PROJECT_MANAGER"||role.value==="IMPLEMENTATION_MEMBER"); const isManager=computed(()=>role.value==="PROJECT_MANAGER");
const labels:Record<string,string>={PLANNED:"已计划",OPEN:"进行中",CLOSED:"已关闭",CANCELLED:"已取消"};
function iso(value:string){return value?new Date(value).toISOString():null} function local(value:string|null){return value?new Date(value).toISOString().slice(0,16):""}
function schedule():SurveyRoundScheduleInput{return{scheduled_start_at:iso(editForm.start),scheduled_end_at:iso(editForm.end),location_note:editForm.location.trim()||null}}
function clearOperation(){operation.value=null;confirmed.value=false;editForm.reason=""}
async function load(next:SurveyRoundCursor|null=null,replace=false){if(!mounted||!identity||identity.password_change_required||busy.value||mutationBusy.value)return;const current=++generation;busy.value=true;error.value="";
 try{const page=await rounds.list(projectId.value,50,next);if(!mounted||current!==generation)return;items.value=replace?page.items:Object.freeze([...items.value,...page.items]);cursor.value=page.next_cursor;loaded.value=true}
 catch(e){if(mounted&&current===generation){if(replace)items.value=[];cursor.value=null;error.value=e instanceof SurveyRoundError?e.message:"暂时无法读取调研轮次。"}}
 finally{if(mounted&&current===generation)busy.value=false}}
async function show(id:string){if(!mounted||detailBusy.value||mutationBusy.value)return;const current=++generation;detailBusy.value=true;detailError.value="";clearOperation();try{const v=await rounds.get(projectId.value,id);if(mounted&&current===generation)detail.value=v}catch(e){if(mounted&&current===generation){detail.value=null;detailError.value=e instanceof SurveyRoundError?e.message:"暂时无法读取轮次详情。"}}finally{if(mounted&&current===generation)detailBusy.value=false}}
function begin(kind:"patch"|"open"|"close"|"cancel"){if(!detail.value)return;operation.value=kind;confirmed.value=false;editForm.start=local(detail.value.scheduled_start_at);editForm.end=local(detail.value.scheduled_end_at);editForm.location=detail.value.location_note??"";editForm.reason="";mutationError.value="";message.value=""}
function makeKey(kind:string){return `survey-round-${kind}-${crypto.randomUUID()}`}
async function submitCreate(){if(!canCreate.value||busy.value||detailBusy.value||mutationBusy.value)return;let body;try{body={survey_id:createForm.surveyId.trim(),survey_version_id:createForm.versionId.trim(),scheduled_start_at:iso(createForm.start),scheduled_end_at:iso(createForm.end),location_note:createForm.location.trim()||null}}catch{mutationError.value="计划时间无效。";return}await mutate({project:projectId.value,actor:identity!.user.user_id,roundId:null,operation:"create",etag:null,key:makeKey("create"),body})}
async function submitOperation(){const item=detail.value;if(!item||!operation.value||!confirmed.value||mutationBusy.value)return;if(operation.value==="patch"){let body;try{body=schedule()}catch{mutationError.value="计划时间无效。";return}await patch(item,body);return}const kind=operation.value;const body=kind==="cancel"?{reason:editForm.reason.trim()}:null;await mutate({project:projectId.value,actor:identity!.user.user_id,roundId:item.survey_round_id,operation:kind,etag:item.etag,key:makeKey(kind),body})}
async function patch(item:SurveyRoundView,body:SurveyRoundScheduleInput){const current=++generation;mutationBusy.value=true;mutationError.value="";message.value="";try{await writes.patch(projectId.value,item.survey_round_id,item.etag,body);if(!mounted||current!==generation)return;message.value="计划已提交；以下内容来自服务器重新读取。";clearOperation();mutationBusy.value=false;await refresh(item.survey_round_id)}catch(e){if(mounted&&current===generation){mutationError.value=e instanceof SurveyRoundError?e.message:"计划修改结果无法确认，请重新读取。";detail.value=null}}finally{if(mounted&&current===generation)mutationBusy.value=false}}
async function mutate(attempt:Pending){const current=++generation;pending.value=attempt;mutationBusy.value=true;mutationError.value="";message.value="";try{let result;if(attempt.operation==="create")result=await writes.create(attempt.project,attempt.body as never,attempt.key);else if(attempt.operation==="open")result=await writes.open(attempt.project,attempt.roundId!,attempt.etag!,attempt.key);else if(attempt.operation==="close")result=await writes.close(attempt.project,attempt.roundId!,attempt.etag!,attempt.key);else result=await writes.cancel(attempt.project,attempt.roundId!,attempt.etag!,attempt.key,String(attempt.body?.reason??""));
 if(!mounted||current!==generation||attempt.project!==projectId.value||attempt.actor!==session.view?.user.user_id)return;pending.value=null;createOpen.value=false;clearOperation();message.value="操作已提交；以下状态来自服务器重新读取。";mutationBusy.value=false;await refresh(result.survey_round_id)}catch(e){if(!mounted||current!==generation)return;if(e instanceof SurveyRoundError&&!e.uncertain){pending.value=null;mutationError.value=e.message}else mutationError.value="操作结果无法确认。已保留原操作号、版本和正文；先重新读取或按原操作重试。";detail.value=null}finally{if(mounted&&current===generation)mutationBusy.value=false}}
async function refresh(roundId:string){items.value=[];cursor.value=null;loaded.value=false;await load(null,true);await show(roundId)}
watch(()=>route.params.projectId,()=>{generation+=1;items.value=[];cursor.value=null;detail.value=null;loaded.value=false;error.value="";detailError.value="";mutationError.value="";message.value="";pending.value=null;busy.value=false;detailBusy.value=false;mutationBusy.value=false;clearOperation();void load(null,true)},{immediate:true});
onUnmounted(()=>{mounted=false;generation+=1;pending.value=null});
</script>

<template><section class="rounds" aria-labelledby="round-title" :aria-busy="busy||detailBusy||mutationBusy"><p class="section-kicker">项目调研</p><h1 id="round-title">调研轮次工作台</h1>
<p class="warning"><strong>PLANNED 和 OPEN 均不是客户确认事实。</strong> 只有服务器重新验证全部有效响应与当前证据后，轮次才能 CLOSED；界面按钮不替代该证明。</p>
<p><RouterLink :to="{name:'project-surveys',params:{projectId}}">返回调研定义</RouterLink> · <RouterLink :to="{name:'project-survey-conclusions',params:{projectId}}">进入调研结论工作台</RouterLink> · <RouterLink :to="{name:'project-detail',params:{projectId}}">返回项目详情</RouterLink></p>
<template v-if="!identity"><p role="status">尚未读取当前身份。请先登录。</p><RouterLink to="/login">前往登录</RouterLink></template>
<template v-else-if="identity.password_change_required"><p role="status">当前账户须先修改密码，暂不能读取调研轮次。</p></template>
<template v-else><div class="toolbar"><button :disabled="busy||mutationBusy" @click="load(null,true)">{{busy?'正在读取…':'刷新轮次'}}</button><button v-if="canCreate" :disabled="busy||detailBusy||mutationBusy" @click="createOpen=!createOpen">新建计划轮次</button></div>
<form v-if="createOpen&&canCreate" @submit.prevent="submitCreate"><h2>新建计划轮次</h2><p>只能绑定已批准且属于当前项目的固定调研版本；服务器将重新核验。</p><label>调研定义 ID<input v-model.trim="createForm.surveyId" required></label><label>批准版本 ID<input v-model.trim="createForm.versionId" required></label><div class="two"><label>计划开始<input v-model="createForm.start" type="datetime-local"></label><label>计划结束<input v-model="createForm.end" type="datetime-local"></label></div><label>地点说明<input v-model.trim="createForm.location" maxlength="1000"></label><button :disabled="busy||detailBusy||mutationBusy">创建并重新读取</button></form>
<p v-if="error" role="alert">{{error}}</p><p v-if="mutationError" role="alert">{{mutationError}}</p><p v-if="message" role="status">{{message}}</p><button v-if="pending" :disabled="mutationBusy" @click="mutate(pending)">使用原操作号、版本和正文重试</button>
<p v-if="loaded&&!items.length" role="status">当前项目没有可见的调研轮次。</p><ol v-if="items.length" aria-label="项目调研轮次"><li v-for="item in items" :key="item.survey_round_id"><strong>第 {{item.round_no}} 轮 · {{labels[item.state]}}</strong><span>调研版本 {{item.survey_version_id}}</span><span>固定来源 {{item.source_record_count}} 条 · {{item.etag}}</span><button :disabled="detailBusy||mutationBusy" @click="show(item.survey_round_id)">查看与操作</button></li></ol><button v-if="cursor" :disabled="busy" @click="load(cursor)">加载更多</button>
<p v-if="detailBusy" role="status">正在读取轮次详情…</p><p v-if="detailError" role="alert">{{detailError}}</p><article v-if="detail"><h2>第 {{detail.round_no}} 轮 · {{labels[detail.state]}}</h2><dl><dt>轮次 ID</dt><dd>{{detail.survey_round_id}}</dd><dt>调研版本</dt><dd>{{detail.survey_version_id}}</dd><dt>计划</dt><dd>{{detail.scheduled_start_at?new Date(detail.scheduled_start_at).toLocaleString('zh-CN')+' 至 '+new Date(detail.scheduled_end_at!).toLocaleString('zh-CN'):'未设置'}}</dd><dt>地点</dt><dd>{{detail.location_note??'未设置'}}</dd><dt>固定来源</dt><dd>{{detail.source_record_count}} 条</dd><dt>当前版本</dt><dd>{{detail.etag}}</dd></dl>
<p v-if="detail.state==='CLOSED'" role="status">关闭证明指纹：{{detail.close_report_fingerprint}}</p><p v-if="detail.state==='CANCELLED'">取消原因：{{detail.cancellation_reason}}</p>
<p><RouterLink :to="{name:'project-survey-assignments',params:{projectId,roundId:detail.survey_round_id}}">进入本轮分配与答复工作台</RouterLink></p>
<div class="toolbar"><button v-if="detail.state==='PLANNED'&&canCreate" @click="begin('patch')">修改计划</button><button v-if="detail.state==='PLANNED'&&isManager" @click="begin('open')">开始轮次</button><button v-if="detail.state==='OPEN'&&isManager" @click="begin('close')">验证并关闭</button><button v-if="detail.state==='PLANNED'&&isManager" @click="begin('cancel')">取消轮次</button></div>
<form v-if="operation" @submit.prevent="submitOperation"><h3>{{operation==='patch'?'修改计划':operation==='open'?'开始轮次':operation==='close'?'验证并关闭轮次':'取消轮次'}}</h3><template v-if="operation==='patch'"><div class="two"><label>计划开始<input v-model="editForm.start" type="datetime-local"></label><label>计划结束<input v-model="editForm.end" type="datetime-local"></label></div><label>地点说明<input v-model.trim="editForm.location" maxlength="1000"></label></template><label v-if="operation==='cancel'">取消原因<textarea v-model.trim="editForm.reason" required maxlength="2000"></textarea></label><p v-if="operation==='close'" class="warning">提交后服务器将锁定并重验所有 Assignment、Response、Evidence 和固定来源；不完整或漂移会拒绝关闭。</p><label><input v-model="confirmed" type="checkbox">我已核对当前 {{detail.etag}} 版本和本次操作</label><button :disabled="mutationBusy||!confirmed">确认提交并重新读取</button></form>
</article></template></section></template>

<style scoped>.rounds{max-width:62rem;margin:1rem auto;padding:1.5rem;background:#fff;border-radius:1rem}.warning{padding:.8rem 1rem;background:#fff8e9;border-left:.3rem solid #d29b42}.toolbar{display:flex;gap:.5rem;flex-wrap:wrap;margin:.7rem 0}.rounds ol{display:grid;gap:.7rem;padding:0;list-style:none}.rounds li{display:grid;gap:.35rem;padding:1rem;border:1px solid #d8dee7;border-radius:.7rem;overflow-wrap:anywhere}.rounds article,.rounds form{display:grid;gap:.7rem;margin-top:1rem;padding:1rem;border:1px solid #cbd5df;border-radius:.7rem}.rounds label{display:grid;gap:.25rem}.rounds input,.rounds textarea{box-sizing:border-box;width:100%;padding:.5rem}.two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem}.rounds dl{display:grid;grid-template-columns:auto 1fr;gap:.5rem 1rem}.rounds dd{margin:0;overflow-wrap:anywhere}.rounds [role=alert]{color:#a21d25}@media(max-width:48rem){.two{grid-template-columns:1fr}}</style>
