<script setup lang="ts">
import { computed, inject, onUnmounted, reactive, ref, toRaw, watch } from "vue";
import { RouterLink, useRoute } from "vue-router";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { sessionClientKey } from "@/modules/auth/api/sessionContext";
import { ProjectDepartmentReadClient, type ProjectDepartmentView } from "@/modules/project/api/projectDepartmentReadClient";
import { ProjectMemberReadClient, type ProjectMemberView } from "@/modules/project/api/projectMemberReadClient";
import { EvidenceListClient, type EvidenceSummary } from "@/modules/evidence/api/evidenceListClient";
import { SurveyReadClient, type SurveyQuestionView, type SurveyVersionView } from "@/modules/survey/api/surveyReadClient";
import { SurveyRoundReadClient, type SurveyRoundView } from "@/modules/survey/api/surveyRoundClient";
import { SurveyAssignmentError, SurveyAssignmentReadClient, SurveyAssignmentWriteClient,
  type SurveyAssignmentCursor, type SurveyAssignmentView, type SurveyResponseInput,
  type SurveyResponseSource } from "@/modules/survey/api/surveyAssignmentClient";

const props=defineProps<{session?:SessionClient;rounds?:SurveyRoundReadClient;assignments?:SurveyAssignmentReadClient;
  writes?:SurveyAssignmentWriteClient;surveys?:SurveyReadClient;departments?:ProjectDepartmentReadClient;
  members?:ProjectMemberReadClient;evidence?:EvidenceListClient}>();
const session=toRaw(props.session??inject(sessionClientKey,null)??new SessionClient()); const identity=session.view;
const rounds=toRaw(props.rounds??new SurveyRoundReadClient()), assignments=toRaw(props.assignments??new SurveyAssignmentReadClient());
const writes=toRaw(props.writes??new SurveyAssignmentWriteClient(session)), surveys=toRaw(props.surveys??new SurveyReadClient());
const departmentsApi=toRaw(props.departments??new ProjectDepartmentReadClient()), membersApi=toRaw(props.members??new ProjectMemberReadClient());
const evidenceApi=toRaw(props.evidence??new EvidenceListClient()); const route=useRoute(); let mounted=true,generation=0;
const projectId=computed(()=>typeof route.params.projectId==="string"?route.params.projectId:"");
const roundId=computed(()=>typeof route.params.roundId==="string"?route.params.roundId:"");
const role=computed(()=>identity?.authorized_projects.find(x=>x.project_id===projectId.value)?.role??null);
const canManage=computed(()=>role.value==="PROJECT_MANAGER"||role.value==="IMPLEMENTATION_MEMBER");
const round=ref<SurveyRoundView|null>(null),definition=ref<SurveyVersionView|null>(null);
const departments=ref<readonly ProjectDepartmentView[]>([]),members=ref<readonly ProjectMemberView[]>([]),evidence=ref<readonly EvidenceSummary[]>([]);
const items=ref<readonly SurveyAssignmentView[]>([]),cursor=ref<SurveyAssignmentCursor|null>(null),detail=ref<SurveyAssignmentView|null>(null);
const loading=ref(false),detailBusy=ref(false),mutationBusy=ref(false),loaded=ref(false),error=ref(""),detailError=ref(""),mutationError=ref(""),message=ref("");
const createOpen=ref(false),confirmed=ref(false),reviewKind=ref<"submit"|"validate"|"return"|null>(null);
const createForm=reactive({departmentId:"",assigneeUserId:""});
const answerForm=reactive({questionId:"",source:"SELF_SERVICE" as SurveyResponseSource,raw:"",text:"",single:"",multiple:[] as string[],date:"",number:"",evidenceIds:[] as string[],projectRecordEvidenceId:""});
const returnComment=ref("");
type Pending={kind:"create"|"response"|"submit"|"validate"|"return";assignmentId:string|null;etag:string|null;key:string;body:Record<string,unknown>|null};
const pending=ref<Pending|null>(null);
const labels:Record<string,string>={ASSIGNED:"待填写",IN_PROGRESS:"填写中",SUBMITTED:"待审核",VALIDATED:"已确认",RETURNED:"已退回"};
const activeDepartments=computed(()=>departments.value.filter(x=>x.state==="ACTIVE"&&definition.value?.target_departments.some(t=>t.department_id===x.department_id)));
const availableMembers=computed(()=>members.value.filter(x=>x.state==="ACTIVE"&&x.department.department_id===createForm.departmentId));
const eligibleEvidence=computed(()=>evidence.value.filter(x=>x.eligibility_state==="ELIGIBLE"));
const question=computed(()=>definition.value?.questions.find(x=>x.question_id===answerForm.questionId)??null);
const latestByQuestion=computed(()=>{const result=new Map<string,string>();for(const item of detail.value?.responses??[])result.set(item.question_id,item.survey_response_id);return result});
function key(kind:string){return `survey-assignment-${kind}-${crypto.randomUUID()}`}
function resetAnswer(){answerForm.questionId=definition.value?.questions[0]?.question_id??"";answerForm.source="SELF_SERVICE";answerForm.raw="";answerForm.text="";answerForm.single="";answerForm.multiple=[];answerForm.date="";answerForm.number="";answerForm.evidenceIds=[];answerForm.projectRecordEvidenceId=""}
async function load(next:SurveyAssignmentCursor|null=null,replace=false){if(!mounted||!identity||identity.password_change_required||loading.value||mutationBusy.value)return;const current=++generation;loading.value=true;error.value="";try{if(!round.value){const r=await rounds.get(projectId.value,roundId.value);const [v,d,m,e]=await Promise.all([surveys.getVersion(projectId.value,r.survey_id,r.survey_version_id),departmentsApi.list(projectId.value),membersApi.list(projectId.value),evidenceApi.list({kind:"PROJECT",projectId:projectId.value})]);if(!mounted||current!==generation)return;round.value=r;definition.value=v;departments.value=d.items;members.value=m.items;evidence.value=e.items;resetAnswer()}const page=await assignments.list(projectId.value,roundId.value,50,next);if(!mounted||current!==generation)return;items.value=replace?page.items:Object.freeze([...items.value,...page.items]);cursor.value=page.next_cursor;loaded.value=true}catch(e){if(mounted&&current===generation){if(replace)items.value=[];cursor.value=null;error.value=e instanceof Error?e.message:"暂时无法读取调研分配。"}}finally{if(mounted&&current===generation)loading.value=false}}
async function show(id:string){if(!mounted||detailBusy.value||mutationBusy.value)return;const current=++generation;detailBusy.value=true;detailError.value="";reviewKind.value=null;confirmed.value=false;try{const value=await assignments.get(projectId.value,roundId.value,id);if(mounted&&current===generation){detail.value=value;resetAnswer()}}catch(e){if(mounted&&current===generation){detail.value=null;detailError.value=e instanceof Error?e.message:"暂时无法读取分配详情。"}}finally{if(mounted&&current===generation)detailBusy.value=false}}
function answerValue(q:SurveyQuestionView){if(q.answer_type==="TEXT")return answerForm.text;if(q.answer_type==="SINGLE_CHOICE")return answerForm.single;if(q.answer_type==="MULTIPLE_CHOICE")return [...answerForm.multiple];if(q.answer_type==="DATE")return answerForm.date;if(q.answer_type==="NUMBER"){const value=Number(answerForm.number);if(!Number.isFinite(value))throw new Error("请输入有效数字。");return value}return null}
async function createAssignment(){if(!canManage.value||!createForm.departmentId||mutationBusy.value)return;await execute({kind:"create",assignmentId:null,etag:null,key:key("create"),body:{departmentId:createForm.departmentId,assigneeUserId:createForm.assigneeUserId||null}})}
async function recordAnswer(){const item=detail.value,q=question.value;if(!item||!q||mutationBusy.value)return;let value;try{value=answerValue(q)}catch(e){mutationError.value=e instanceof Error?e.message:"答复内容无效。";return}const source=answerForm.source;const body={question_id:q.question_id,response_source:source,raw_answer:answerForm.raw.trim()||null,answer_value:value,evidence_ids:[...answerForm.evidenceIds],project_record_evidence_id:source==="FACILITATED_RECORD"?(answerForm.projectRecordEvidenceId||null):null,correction_of_response_id:latestByQuestion.value.get(q.question_id)??null};await execute({kind:"response",assignmentId:item.survey_assignment_id,etag:item.etag,key:key("response"),body})}
async function review(){const item=detail.value,kind=reviewKind.value;if(!item||!kind||!confirmed.value||mutationBusy.value)return;await execute({kind,assignmentId:item.survey_assignment_id,etag:item.etag,key:key(kind),body:kind==="return"?{comment:returnComment.value.trim()}:null})}
async function execute(attempt:Pending){const current=++generation;pending.value=attempt;mutationBusy.value=true;mutationError.value="";message.value="";try{if(attempt.kind==="create")await writes.create(projectId.value,roundId.value,String(attempt.body?.departmentId??""),attempt.body?.assigneeUserId as string|null,attempt.key);else if(attempt.kind==="response")await writes.record(projectId.value,roundId.value,attempt.assignmentId!,attempt.etag!,attempt.body as unknown as SurveyResponseInput,attempt.key);else if(attempt.kind==="submit")await writes.submit(projectId.value,roundId.value,attempt.assignmentId!,attempt.etag!,attempt.key);else if(attempt.kind==="validate")await writes.validate(projectId.value,roundId.value,attempt.assignmentId!,attempt.etag!,attempt.key);else await writes.returnAssignment(projectId.value,roundId.value,attempt.assignmentId!,attempt.etag!,attempt.key,String(attempt.body?.comment??""));if(!mounted||current!==generation)return;pending.value=null;createOpen.value=false;reviewKind.value=null;confirmed.value=false;message.value="操作已提交；以下事实来自服务器重新读取。";mutationBusy.value=false;const selected=attempt.assignmentId;items.value=[];cursor.value=null;loaded.value=false;await load(null,true);if(selected)await show(selected)}catch(e){if(!mounted||current!==generation)return;if(e instanceof SurveyAssignmentError&&!e.uncertain){pending.value=null;mutationError.value=e.message}else mutationError.value="操作结果无法确认。已保留原操作号、版本与正文；请先重新读取或按原操作重试。";detail.value=null}finally{if(mounted&&current===generation)mutationBusy.value=false}}
watch(()=>[route.params.projectId,route.params.roundId],()=>{generation+=1;round.value=null;definition.value=null;departments.value=[];members.value=[];evidence.value=[];items.value=[];cursor.value=null;detail.value=null;loaded.value=false;error.value="";detailError.value="";mutationError.value="";message.value="";pending.value=null;loading.value=false;detailBusy.value=false;mutationBusy.value=false;void load(null,true)},{immediate:true});
onUnmounted(()=>{mounted=false;generation+=1;pending.value=null});
</script>

<template><section class="assignments" aria-labelledby="assignment-title" :aria-busy="loading||detailBusy||mutationBusy"><p class="section-kicker">项目调研</p><h1 id="assignment-title">调研分配与答复工作台</h1>
<p class="warning"><strong>AI 建议和页面录入都不是客户确认事实。</strong> SUBMITTED 仍需项目管理角色按当前证据重新验证；只有 VALIDATED 才进入轮次关闭证明。</p>
<p><RouterLink :to="{name:'project-survey-rounds',params:{projectId}}">返回调研轮次</RouterLink> · <RouterLink :to="{name:'project-evidence',params:{projectId}}">管理项目证据</RouterLink></p>
<template v-if="!identity"><p role="status">尚未读取当前身份。请先登录。</p><RouterLink to="/login">前往登录</RouterLink></template><template v-else-if="identity.password_change_required"><p role="status">当前账户须先修改密码，暂不能读取调研答复。</p></template>
<template v-else><p v-if="round">第 {{round.round_no}} 轮 · {{round.state}} · 固定版本 {{round.survey_version_id}}</p><div class="toolbar"><button :disabled="loading||mutationBusy" @click="load(null,true)">{{loading?'正在读取…':'刷新分配'}}</button><button v-if="canManage&&round?.state==='OPEN'" :disabled="loading||mutationBusy" @click="createOpen=!createOpen">新建分配</button></div>
<form v-if="createOpen&&canManage" @submit.prevent="createAssignment"><h2>新建目标分配</h2><label>目标部门<select v-model="createForm.departmentId" required><option value="">请选择固定目标部门</option><option v-for="department in activeDepartments" :key="department.department_id" :value="department.department_id">{{department.name}}（{{department.code}}）</option></select></label><label>受访人<select v-model="createForm.assigneeUserId"><option value="">部门级分配（由当前部门成员填写）</option><option v-for="member in availableMembers" :key="member.user.user_id" :value="member.user.user_id">{{member.user.display_name}} · {{member.role}}</option></select></label><p>部门和受访人均由服务器按当前项目成员事实重新核验。</p><button :disabled="mutationBusy">创建并重新读取</button></form>
<p v-if="error" role="alert">{{error}}</p><p v-if="mutationError" role="alert">{{mutationError}}</p><p v-if="message" role="status">{{message}}</p><button v-if="pending" :disabled="mutationBusy" @click="execute(pending)">使用原操作号、版本和正文重试</button>
<p v-if="loaded&&!items.length" role="status">本轮没有当前账户可见的调研分配。</p><ol v-if="items.length" aria-label="调研分配"><li v-for="item in items" :key="item.survey_assignment_id"><strong>{{labels[item.state]}}</strong><span>部门：{{departments.find(x=>x.department_id===item.department_id)?.name??item.department_id}}</span><span>受访人：{{members.find(x=>x.user.user_id===item.assignee_user_id)?.user.display_name??(item.assignee_user_id?'当前不可见成员':'部门成员')}}</span><span>有效答复 {{item.response_count}} 条 · {{item.etag}}</span><button :disabled="detailBusy||mutationBusy" @click="show(item.survey_assignment_id)">查看与填写</button></li></ol><button v-if="cursor" :disabled="loading" @click="load(cursor)">加载更多</button>
<p v-if="detailBusy" role="status">正在读取分配详情…</p><p v-if="detailError" role="alert">{{detailError}}</p><article v-if="detail"><h2>{{labels[detail.state]}} · {{detail.etag}}</h2><p v-if="detail.return_comment" class="warning">最近退回意见：{{detail.return_comment}}</p><h3>当前答复历史</h3><p v-if="!detail.responses?.length">尚无答复。</p><ol v-else><li v-for="response in detail.responses" :key="response.survey_response_id"><strong>{{definition?.questions.find(x=>x.question_id===response.question_id)?.question_text??response.question_id}}</strong><span>{{response.response_source==='FACILITATED_RECORD'?'面对面记录':'自主填写'}} · {{new Date(response.recorded_at).toLocaleString('zh-CN')}}</span><span>答复：{{JSON.stringify(response.answer_value)}}</span><span v-if="response.evidence.length">证据 {{response.evidence.length}} 项</span></li></ol>
<form v-if="round?.state==='OPEN'&&['ASSIGNED','IN_PROGRESS','RETURNED'].includes(detail.state)" @submit.prevent="recordAnswer"><h3>追加答复{{detail.state==='RETURNED'?' / 更正':''}}</h3><label>问题<select v-model="answerForm.questionId" required><option v-for="q in definition?.questions??[]" :key="q.question_id" :value="q.question_id">{{q.sequence_no+1}}. {{q.question_text}}{{q.required?'（必答）':''}}</option></select></label><template v-if="question"><p>{{question.objective}}；期望输出：{{question.expected_output}}</p><p v-if="question.condition_rule" class="hint">这是条件题，是否生效由服务器根据前置答复计算。</p><label v-if="question.answer_type==='TEXT'">文本答复<textarea v-model="answerForm.text" required maxlength="20000"></textarea></label><label v-else-if="question.answer_type==='SINGLE_CHOICE'">单选<select v-model="answerForm.single" required><option value="">请选择</option><option v-for="option in question.options" :key="option.option_code" :value="option.option_code">{{option.label}}</option></select></label><fieldset v-else-if="question.answer_type==='MULTIPLE_CHOICE'"><legend>多选</legend><label v-for="option in question.options" :key="option.option_code"><input v-model="answerForm.multiple" type="checkbox" :value="option.option_code">{{option.label}}</label></fieldset><label v-else-if="question.answer_type==='DATE'">日期<input v-model="answerForm.date" type="date" required></label><label v-else-if="question.answer_type==='NUMBER'">数值<input v-model="answerForm.number" type="number" step="any" required></label><p v-else>附件型答复必须选择至少一个当前有效证据，结构化值由服务器生成。</p></template><label>记录方式<select v-model="answerForm.source"><option value="SELF_SERVICE">自主填写</option><option v-if="role==='IMPLEMENTATION_MEMBER'" value="FACILITATED_RECORD">实施人员面对面代录</option></select></label><label>原始记录摘要（可选）<textarea v-model="answerForm.raw" maxlength="20000"></textarea></label><fieldset><legend>引用当前有效项目证据</legend><p v-if="!eligibleEvidence.length">当前列表没有有效证据，请先前往证据页维护。</p><label v-for="entry in eligibleEvidence" :key="entry.evidence_id"><input v-model="answerForm.evidenceIds" type="checkbox" :value="entry.evidence_id">{{entry.display_label}}<small v-if="entry.display_excerpt"> — {{entry.display_excerpt}}</small></label></fieldset><label v-if="answerForm.source==='FACILITATED_RECORD'">面对面 PROJECT_RECORD 证据<select v-model="answerForm.projectRecordEvidenceId" required><option value="">请选择；服务器将核验文档类别</option><option v-for="entry in eligibleEvidence" :key="entry.evidence_id" :value="entry.evidence_id">{{entry.display_label}}</option></select></label><p v-if="latestByQuestion.has(answerForm.questionId)">本次将作为该问题最新答复的追加式更正，原记录不会覆盖。</p><button :disabled="mutationBusy">提交答复并重新读取</button></form>
<div class="toolbar"><button v-if="['IN_PROGRESS','RETURNED'].includes(detail.state)" @click="reviewKind='submit';confirmed=false">提交审核</button><button v-if="detail.state==='SUBMITTED'&&canManage" @click="reviewKind='validate';confirmed=false">确认有效</button><button v-if="detail.state==='SUBMITTED'&&canManage" @click="reviewKind='return';confirmed=false">退回补充</button></div><form v-if="reviewKind" @submit.prevent="review"><h3>{{reviewKind==='submit'?'提交审核':reviewKind==='validate'?'确认答复有效':'退回补充'}}</h3><label v-if="reviewKind==='return'">退回意见<textarea v-model.trim="returnComment" required maxlength="2000"></textarea></label><p v-else class="warning">服务器将按固定问题、条件、必答、ValidationRule 与当前 Evidence 重新计算，不接受页面自报完整。</p><label><input v-model="confirmed" type="checkbox">我已核对当前 {{detail.etag}} 版本和本次操作</label><button :disabled="mutationBusy||!confirmed">确认提交并重新读取</button></form></article></template></section></template>

<style scoped>.assignments{max-width:68rem;margin:1rem auto;padding:1.5rem;background:#fff;border-radius:1rem}.warning{padding:.8rem 1rem;background:#fff8e9;border-left:.3rem solid #d29b42}.hint{color:#4a5968}.toolbar{display:flex;gap:.5rem;flex-wrap:wrap;margin:.7rem 0}.assignments>ol,.assignments article>ol{display:grid;gap:.7rem;padding:0;list-style:none}.assignments li{display:grid;gap:.35rem;padding:1rem;border:1px solid #d8dee7;border-radius:.7rem;overflow-wrap:anywhere}.assignments article,.assignments form{display:grid;gap:.7rem;margin-top:1rem;padding:1rem;border:1px solid #cbd5df;border-radius:.7rem}.assignments label{display:grid;gap:.25rem}.assignments input,.assignments textarea,.assignments select{box-sizing:border-box;width:100%;padding:.5rem}.assignments fieldset label{display:flex;grid-template-columns:auto 1fr;align-items:start}.assignments fieldset input{width:auto;margin:.2rem .5rem 0 0}.assignments [role=alert]{color:#a21d25}</style>
