import { describe, expect, it, vi } from "vitest";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { SurveyRoundError, SurveyRoundReadClient, SurveyRoundWriteClient, parseSurveyRound } from "./surveyRoundClient";

const actor="01234567-89ab-4cde-8123-456789abcdef",project="11234567-89ab-4cde-8123-456789abcdef";
const survey="21234567-89ab-4cde-8123-456789abcdef",version="31234567-89ab-4cde-8123-456789abcdef",round="41234567-89ab-4cde-8123-456789abcdef";
const source="51234567-89ab-4cde-8123-456789abcdef",document="61234567-89ab-4cde-8123-456789abcdef",documentVersion="71234567-89ab-4cde-8123-456789abcdef",evidence="81234567-89ab-4cde-8123-456789abcdef";
const now="2026-10-06T12:00:00Z",key="survey-round-attempt-0001";
function item(state="PLANNED",etag='"v0"',detail=false){const lifecycle=state==="PLANNED"?{}:state==="OPEN"?{opened_by:actor,opened_at:now}:state==="CLOSED"?{opened_by:actor,opened_at:now,closed_by:actor,closed_at:now,close_report_fingerprint:"a".repeat(64)}:{cancelled_by:actor,cancelled_at:now,cancellation_reason:"取消重复轮次"};return{survey_round_id:round,survey_id:survey,survey_version_id:version,project_id:project,round_no:1,state,scheduled_start_at:null,scheduled_end_at:null,location_note:null,opened_by:null,opened_at:null,closed_by:null,closed_at:null,close_report_fingerprint:null,cancelled_by:null,cancelled_at:null,cancellation_reason:null,created_by:actor,created_at:now,updated_by:actor,updated_at:now,etag,source_record_count:detail?1:0,...lifecycle,...(detail?{source_records:[{round_source_record_ref_id:source,question_id:null,document_id:document,document_version_id:documentVersion,evidence_id:evidence,observed_evidence_lock_version:0,content_fingerprint:"b".repeat(64),recorded_by:actor,recorded_at:now,ordinal:0}]}:{})}}
function envelope(data:unknown,status=200,etag='"v0"',location?:string){return new Response(JSON.stringify({data,trace_id:actor}),{status,headers:{"Content-Type":"application/json",ETag:etag,...(location?{Location:location}:{})}})}
function failure(status:number,code:string){return new Response(JSON.stringify({error:{code,message:"private"},trace_id:actor}),{status,headers:{"Content-Type":"application/json"}})}
async function writer(...responses:Response[]){const session={user:{user_id:actor,username_display:"项目经理"},deployment_role:"NONE",password_change_required:false,authorized_projects:[{project_id:project,name:"项目",role:"PROJECT_MANAGER"}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)};const fetcher=vi.fn().mockResolvedValueOnce(envelope(session));responses.forEach(x=>fetcher.mockResolvedValueOnce(x));const identity=new SessionClient(fetcher as typeof fetch);await identity.login("manager","synthetic");return{api:new SurveyRoundWriteClient(identity),fetcher}}

describe("SurveyRound clients",()=>{
 it("strictly reads pages and detail with frozen source proof",async()=>{const created={...item(),updated_by:null};const fetcher=vi.fn().mockResolvedValueOnce(envelope({items:[created],next_cursor:null,has_more:false})).mockResolvedValueOnce(envelope(item("PLANNED",'"v0"',true)));const api=new SurveyRoundReadClient(fetcher as typeof fetch);expect((await api.list(project)).items[0]?.updated_by).toBeNull();const detail=await api.get(project,round);expect(detail.source_records?.[0]?.evidence_id).toBe(evidence);expect(Object.isFrozen(detail.source_records?.[0])).toBe(true);expect(fetcher.mock.calls[0][0]).toContain("page_size=50")});
 it("rejects lifecycle drift and malformed detail",()=>{expect(()=>parseSurveyRound({...item("CLOSED",'"v2"',true),close_report_fingerprint:null},project,round,true)).toThrowError(SurveyRoundError);expect(()=>parseSurveyRound({...item(),extra:true},project)).toThrowError(SurveyRoundError)});
 it("uses CSRF, key and ETag for all five writes",async()=>{const location=`/api/v1/projects/${project}/survey-rounds/${round}`;const replies=[envelope(item("PLANNED",'"v0"',true),201,'"v0"',location),envelope(item("PLANNED",'"v1"',true),200,'"v1"'),envelope(item("OPEN",'"v1"',true),200,'"v1"'),envelope(item("CLOSED",'"v2"',true),200,'"v2"'),envelope(item("CANCELLED",'"v1"',true),200,'"v1"')];const{api,fetcher}=await writer(...replies);await api.create(project,{survey_id:survey,survey_version_id:version,scheduled_start_at:null,scheduled_end_at:null,location_note:null},key);await api.patch(project,round,'"v0"',{scheduled_start_at:null,scheduled_end_at:null,location_note:"会议室"});await api.open(project,round,'"v0"',key);await api.close(project,round,'"v1"',key);await api.cancel(project,round,'"v0"',key,"取消重复轮次");expect(fetcher.mock.calls.slice(1).map(x=>x[0])).toEqual([`/api/v1/projects/${project}/survey-rounds`,...(["",":open",":close",":cancel"].map((x,i)=>i===0?`/api/v1/projects/${project}/survey-rounds/${round}`:`/api/v1/projects/${project}/survey-rounds/${round}${x}`))]);expect(fetcher.mock.calls[2][1]).toMatchObject({method:"PATCH",headers:{"If-Match":'"v0"',"X-CSRF-Token":"a".repeat(64)}});expect(fetcher.mock.calls[3][1]).not.toHaveProperty("body");expect(fetcher.mock.calls[5][1]).toMatchObject({headers:{"Idempotency-Key":key}})});
 it.each([[409,"CONFLICT_VERSION"],[409,"CONFLICT_STATE"],[409,"CONFLICT_IDEMPOTENCY"],[422,"SURVEY_ROUND_INCOMPLETE"]] as const)("maps safe close error %s %s",async(status,code)=>{const caught=await(await writer(failure(status,code==="SURVEY_ROUND_INCOMPLETE"?"VALIDATION_FAILED":code))).api.close(project,round,'"v0"',key).catch(x=>x);expect(caught).toBeInstanceOf(SurveyRoundError);expect(caught.code).toBe(code);expect(String(caught)).not.toContain("private")});
 it("never retries an uncertain write and validates paired schedule",async()=>{const{api,fetcher}=await writer();await expect(api.open(project,round,'"v0"',key)).rejects.toMatchObject({code:"SURVEY_ROUND_UNAVAILABLE",uncertain:true});expect(fetcher).toHaveBeenCalledTimes(2);await expect(api.create(project,{survey_id:survey,survey_version_id:version,scheduled_start_at:now,scheduled_end_at:null,location_note:null},key)).rejects.toMatchObject({code:"SURVEY_ROUND_INVALID_INPUT"})});
 it("invokes the supplied transport without a SessionClient receiver",async()=>{let receiver:unknown="unset";const replies=[envelope({user:{user_id:actor,username_display:"项目经理"},deployment_role:"NONE",password_change_required:false,authorized_projects:[{project_id:project,name:"项目",role:"PROJECT_MANAGER"}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)}),envelope(item("PLANNED",'"v0"',true),201,'"v0"',`/api/v1/projects/${project}/survey-rounds/${round}`)];const fetcher=function(this:unknown){receiver=this;return Promise.resolve(replies.shift()!)} as typeof fetch;const identity=new SessionClient(fetcher);await identity.login("manager","synthetic");receiver="unset";await new SurveyRoundWriteClient(identity).create(project,{survey_id:survey,survey_version_id:version,scheduled_start_at:null,scheduled_end_at:null,location_note:null},key);expect(receiver).toBeUndefined()});
});
