import { describe, expect, it, vi } from "vitest";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { SurveyAssignmentError, SurveyAssignmentReadClient, SurveyAssignmentWriteClient,
  parseSurveyAssignment } from "./surveyAssignmentClient";

const actor="01234567-89ab-4cde-8123-456789abcdef",project="11234567-89ab-4cde-8123-456789abcdef";
const survey="21234567-89ab-4cde-8123-456789abcdef",version="31234567-89ab-4cde-8123-456789abcdef";
const round="41234567-89ab-4cde-8123-456789abcdef",assignment="51234567-89ab-4cde-8123-456789abcdef";
const department="61234567-89ab-4cde-8123-456789abcdef",question="71234567-89ab-4cde-8123-456789abcdef";
const responseId="81234567-89ab-4cde-8123-456789abcdef",answer="91234567-89ab-4cde-8123-456789abcdef";
const now="2026-10-06T12:00:00Z",key="survey-assignment-attempt-0001";
function item(detail=false){return{survey_assignment_id:assignment,survey_round_id:round,survey_id:survey,survey_version_id:version,project_id:project,department_id:department,assignee_user_id:actor,state:detail?"IN_PROGRESS":"ASSIGNED",submitted_by:null,submitted_at:null,validated_by:null,validated_at:null,returned_by:null,returned_at:null,return_comment:null,created_by:actor,created_at:now,updated_by:detail?actor:null,updated_at:now,etag:detail?'"v1"':'"v0"',response_count:detail?1:0,...(detail?{responses:[{survey_response_id:responseId,question_id:question,response_source:"SELF_SERVICE",round_source_record_ref_id:null,correction_of_response_id:null,recorded_by:actor,recorded_at:now,raw_answer:"answer",answer_value:"answer",evidence:[]}]}:{})}}
function envelope(data:unknown,status=200,etag='"v0"'){return new Response(JSON.stringify({data,trace_id:actor}),{status,headers:{"Content-Type":"application/json",ETag:etag}})}
function failure(status:number,code:string){return new Response(JSON.stringify({error:{code,message:"private"},trace_id:actor}),{status,headers:{"Content-Type":"application/json"}})}
async function writer(...responses:Response[]){const session={user:{user_id:actor,username_display:"项目经理"},deployment_role:"NONE",password_change_required:false,authorized_projects:[{project_id:project,name:"项目",role:"PROJECT_MANAGER"}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)};const fetcher=vi.fn().mockResolvedValueOnce(envelope(session));responses.forEach(x=>fetcher.mockResolvedValueOnce(x));const identity=new SessionClient(fetcher as typeof fetch);await identity.login("manager","synthetic");return{api:new SurveyAssignmentWriteClient(identity),fetcher}}

describe("SurveyAssignment clients",()=>{
 it("strictly reads a round-bound page and response detail",async()=>{const fetcher=vi.fn().mockResolvedValueOnce(envelope({items:[item()],next_cursor:null,has_more:false})).mockResolvedValueOnce(envelope(item(true),200,'"v1"'));const api=new SurveyAssignmentReadClient(fetcher as typeof fetch);expect((await api.list(project,round)).items[0]?.department_id).toBe(department);const detail=await api.get(project,round,assignment);expect(detail.responses?.[0]?.answer_value).toBe("answer");expect(Object.isFrozen(detail.responses)).toBe(true);expect(fetcher.mock.calls[0][0]).toContain("page_size=50")});
 it("rejects parent drift, malformed response count and extra fields",()=>{expect(()=>parseSurveyAssignment({...item(),project_id:actor},project,round)).toThrowError(SurveyAssignmentError);expect(()=>parseSurveyAssignment({...item(true),response_count:2},project,round,assignment,true)).toThrowError(SurveyAssignmentError);expect(()=>parseSurveyAssignment({...item(),extra:true},project,round)).toThrowError(SurveyAssignmentError)});
 it("sends exact five writes with CSRF, key, ETag and bodies",async()=>{const responseWrite={survey_response_id:responseId,survey_answer_id:answer,survey_assignment_id:assignment,survey_round_id:round,survey_version_id:version,project_id:project,question_id:question,response_source:"SELF_SERVICE",round_source_record_ref_id:null,correction_of_response_id:null,recorded_by:actor,recorded_at:now,assignment_state:"IN_PROGRESS",assignment_etag:'"v1"',evidence_count:0};const receipt=(state:string,etag:string,comment?:string|null)=>({survey_assignment_id:assignment,survey_round_id:round,project_id:project,state,etag,...(comment===undefined?{}:{return_comment:comment})});const{api,fetcher}=await writer(envelope(item(),201,'"v0"'),envelope(responseWrite,201,'"v1"'),envelope(receipt("SUBMITTED",'"v2"'),200,'"v2"'),envelope(receipt("VALIDATED",'"v3"',null),200,'"v3"'),envelope(receipt("RETURNED",'"v3"',"请补充"),200,'"v3"'));await api.create(project,round,department,actor,key);await api.record(project,round,assignment,'"v0"',{question_id:question,response_source:"SELF_SERVICE",raw_answer:"answer",answer_value:"answer",evidence_ids:[],project_record_evidence_id:null,correction_of_response_id:null},key);await api.submit(project,round,assignment,'"v1"',key);await api.validate(project,round,assignment,'"v2"',key);await api.returnAssignment(project,round,assignment,'"v2"',key,"请补充");expect(fetcher.mock.calls.slice(1).map(x=>x[0])).toEqual([`/api/v1/projects/${project}/survey-rounds/${round}/assignments`,`/api/v1/projects/${project}/survey-rounds/${round}/assignments/${assignment}/responses`,`/api/v1/projects/${project}/survey-rounds/${round}/assignments/${assignment}:submit`,`/api/v1/projects/${project}/survey-rounds/${round}/assignments/${assignment}:validate`,`/api/v1/projects/${project}/survey-rounds/${round}/assignments/${assignment}:return`]);expect(fetcher.mock.calls[2][1]).toMatchObject({headers:{"If-Match":'"v0"',"Idempotency-Key":key,"X-CSRF-Token":"a".repeat(64)}});expect(fetcher.mock.calls[3][1]).not.toHaveProperty("body")});
 it.each([[409,"CONFLICT_VERSION"],[409,"CONFLICT_STATE"],[422,"SURVEY_ASSIGNMENT_INCOMPLETE"]] as const)("maps safe write error %s %s",async(status,code)=>{const caught=await(await writer(failure(status,code==="SURVEY_ASSIGNMENT_INCOMPLETE"?"VALIDATION_FAILED":code))).api.submit(project,round,assignment,'"v1"',key).catch(x=>x);expect(caught).toBeInstanceOf(SurveyAssignmentError);expect(caught.code).toBe(code);expect(String(caught)).not.toContain("private")});
 it("validates facilitated source and never retries uncertain writes",async()=>{const{api,fetcher}=await writer();await expect(api.record(project,round,assignment,'"v0"',{question_id:question,response_source:"FACILITATED_RECORD",raw_answer:"answer",answer_value:"answer",evidence_ids:[],project_record_evidence_id:null,correction_of_response_id:null},key)).rejects.toMatchObject({code:"SURVEY_ASSIGNMENT_INVALID_INPUT"});await expect(api.submit(project,round,assignment,'"v0"',key)).rejects.toMatchObject({code:"SURVEY_ASSIGNMENT_UNAVAILABLE",uncertain:true});expect(fetcher).toHaveBeenCalledTimes(2)});
});
