import { SessionClient, SessionClientError } from "@/modules/auth/api/sessionClient";

export type SurveyAssignmentState = "ASSIGNED" | "IN_PROGRESS" | "SUBMITTED" | "VALIDATED" | "RETURNED";
export type SurveyResponseSource = "SELF_SERVICE" | "FACILITATED_RECORD";
export type SurveyAssignmentCursor = string & { readonly __family: "survey-assignments" };
export interface SurveyAnswerEvidenceView { readonly evidence_id:string; readonly document_id:string;
  readonly document_version_id:string; readonly observed_evidence_lock_version:number;
  readonly content_fingerprint:string; readonly ordinal:number; }
export interface SurveyResponseView { readonly survey_response_id:string; readonly question_id:string;
  readonly response_source:SurveyResponseSource; readonly round_source_record_ref_id:string|null;
  readonly correction_of_response_id:string|null; readonly recorded_by:string; readonly recorded_at:string;
  readonly raw_answer:string|null; readonly answer_value:unknown; readonly evidence:readonly SurveyAnswerEvidenceView[]; }
export interface SurveyAssignmentView { readonly survey_assignment_id:string; readonly survey_round_id:string;
  readonly survey_id:string; readonly survey_version_id:string; readonly project_id:string;
  readonly department_id:string; readonly assignee_user_id:string|null; readonly state:SurveyAssignmentState;
  readonly submitted_by:string|null; readonly submitted_at:string|null; readonly validated_by:string|null;
  readonly validated_at:string|null; readonly returned_by:string|null; readonly returned_at:string|null;
  readonly return_comment:string|null; readonly created_by:string; readonly created_at:string;
  readonly updated_by:string|null; readonly updated_at:string; readonly etag:string;
  readonly response_count:number; readonly responses?:readonly SurveyResponseView[]; }
export interface SurveyAssignmentPage { readonly items:readonly SurveyAssignmentView[];
  readonly next_cursor:SurveyAssignmentCursor|null; readonly has_more:boolean; }
export interface SurveyResponseInput { readonly question_id:string; readonly response_source:SurveyResponseSource;
  readonly raw_answer:string|null; readonly answer_value:unknown; readonly evidence_ids:readonly string[];
  readonly project_record_evidence_id:string|null; readonly correction_of_response_id:string|null; }
export interface SurveyAssignmentReceipt { readonly survey_assignment_id:string; readonly survey_round_id:string;
  readonly project_id:string; readonly state:SurveyAssignmentState; readonly etag:string; readonly return_comment?:string|null; }

const messages={SURVEY_ASSIGNMENT_INVALID_INPUT:"分配、答复或审核参数无效。",AUTH_RELOGIN_REQUIRED:"提交调研答复前请重新登录。",
  AUTH_CLIENT_BUSY:"正在处理会话操作，请稍候。",AUTH_SESSION_EXPIRED:"会话已失效，请重新登录。",
  AUTH_CSRF_INVALID:"登录状态已变化，请重新登录。",LICENSE_OPERATION_DENIED:"当前许可不允许操作调研分配。",
  RESOURCE_NOT_FOUND:"调研分配不存在，或当前账户无权访问。",PROJECT_ARCHIVED:"项目已归档，不能再操作调研分配。",
  CONFLICT_VERSION:"调研分配已被其他操作更新，请重新读取。",CONFLICT_IDEMPOTENCY:"原操作号与本次输入不一致，已停止提交。",
  CONFLICT_STATE:"当前调研分配状态不允许此操作。",SURVEY_ASSIGNMENT_INCOMPLETE:"当前答复尚未满足提交或确认条件，请补齐必答项与证据。",
  SURVEY_ASSIGNMENT_UNAVAILABLE:"暂时无法确认调研分配结果；请重新读取并核对审计。"} as const;
export type SurveyAssignmentErrorCode=keyof typeof messages;
export class SurveyAssignmentError extends Error { readonly uncertain:boolean;
  constructor(readonly code:SurveyAssignmentErrorCode){super(messages[code]);this.name="SurveyAssignmentError";this.uncertain=code==="SURVEY_ASSIGNMENT_UNAVAILABLE";} }

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const cursor=/^[A-Za-z0-9_-]{1,1024}\.[A-Za-z0-9_-]{43}$/; const etag=/^"v(0|[1-9][0-9]*)"$/; const digest=/^[0-9a-f]{64}$/;
const states=new Set<SurveyAssignmentState>(["ASSIGNED","IN_PROGRESS","SUBMITTED","VALIDATED","RETURNED"]);
function record(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v)}
function exact(v:Record<string,unknown>,keys:readonly string[]){return Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k))}
function id(v:unknown):v is string{return typeof v==="string"&&uuid.test(v)&&v!=="00000000-0000-0000-0000-000000000000"}
function optionalId(v:unknown):v is string|null{return v===null||id(v)}
function instant(v:unknown):v is string{return typeof v==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?Z$/.test(v)&&Number.isFinite(Date.parse(v))}
function optionalInstant(v:unknown):v is string|null{return v===null||instant(v)}
function integer(v:unknown,min=0):v is number{return typeof v==="number"&&Number.isSafeInteger(v)&&v>=min}
function optionalText(v:unknown,max:number):v is string|null{return v===null||typeof v==="string"&&v.length>0&&v.length<=max&&v.trim()===v&&!/\p{C}/u.test(v)}
function frozenJson(v:unknown):unknown{if(Array.isArray(v))return Object.freeze(v.map(frozenJson));if(record(v))return Object.freeze(Object.fromEntries(Object.entries(v).map(([k,x])=>[k,frozenJson(x)])));return v}
const assignmentFields=["survey_assignment_id","survey_round_id","survey_id","survey_version_id","project_id","department_id","assignee_user_id","state","submitted_by","submitted_at","validated_by","validated_at","returned_by","returned_at","return_comment","created_by","created_at","updated_by","updated_at","etag","response_count"] as const;
const evidenceFields=["evidence_id","document_id","document_version_id","observed_evidence_lock_version","content_fingerprint","ordinal"] as const;
const responseFields=["survey_response_id","question_id","response_source","round_source_record_ref_id","correction_of_response_id","recorded_by","recorded_at","raw_answer","answer_value","evidence"] as const;
function evidence(v:unknown,ordinal:number):SurveyAnswerEvidenceView{if(!record(v)||!exact(v,evidenceFields)||!id(v.evidence_id)||!id(v.document_id)||!id(v.document_version_id)||!integer(v.observed_evidence_lock_version)||typeof v.content_fingerprint!=="string"||!digest.test(v.content_fingerprint)||v.ordinal!==ordinal)throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return Object.freeze({...v}) as unknown as SurveyAnswerEvidenceView}
function response(v:unknown):SurveyResponseView{if(!record(v)||!exact(v,responseFields)||!id(v.survey_response_id)||!id(v.question_id)||(v.response_source!=="SELF_SERVICE"&&v.response_source!=="FACILITATED_RECORD")||!optionalId(v.round_source_record_ref_id)||!optionalId(v.correction_of_response_id)||!id(v.recorded_by)||!instant(v.recorded_at)||!optionalText(v.raw_answer,20000)||!Array.isArray(v.evidence))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");let serialized;try{serialized=JSON.stringify(v.answer_value)}catch{throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE")}if(serialized===undefined||new TextEncoder().encode(serialized).length>2*1024*1024)throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return Object.freeze({...v,answer_value:frozenJson(v.answer_value),evidence:Object.freeze(v.evidence.map(evidence))}) as unknown as SurveyResponseView}
export function parseSurveyAssignment(v:unknown,projectId:string,roundId:string,expectedId?:string,detail=false):SurveyAssignmentView{const keys=detail?[...assignmentFields,"responses"]:assignmentFields;if(!record(v)||!exact(v,keys)||!id(v.survey_assignment_id)||expectedId!==undefined&&v.survey_assignment_id!==expectedId||v.project_id!==projectId||v.survey_round_id!==roundId||!id(v.survey_id)||!id(v.survey_version_id)||!id(v.department_id)||!optionalId(v.assignee_user_id)||!states.has(v.state as SurveyAssignmentState)||!optionalId(v.submitted_by)||!optionalInstant(v.submitted_at)||!optionalId(v.validated_by)||!optionalInstant(v.validated_at)||!optionalId(v.returned_by)||!optionalInstant(v.returned_at)||!optionalText(v.return_comment,2000)||!id(v.created_by)||!instant(v.created_at)||!optionalId(v.updated_by)||!instant(v.updated_at)||typeof v.etag!=="string"||!etag.test(v.etag)||!integer(v.response_count)||detail&&!Array.isArray(v.responses))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");const responses=detail?(v.responses as unknown[]).map(response):undefined;if(responses&&responses.length!==v.response_count||responses&&new Set(responses.map(x=>x.survey_response_id)).size!==responses.length||responses&&responses.some((item,index)=>index>0&&item.recorded_at<responses[index-1]!.recorded_at))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return Object.freeze({...v,...(responses?{responses:Object.freeze(responses)}:{})}) as unknown as SurveyAssignmentView}
function envelope(v:unknown){if(!record(v)||!exact(v,["data","trace_id"])||!id(v.trace_id))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return v as {data:unknown;trace_id:string}}
async function payload(r:Response){if(r.headers.get("Content-Type")?.split(";",1)[0].trim().toLowerCase()!=="application/json")throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");try{return await r.json()}catch{throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE")}}
function failure(status:number,v:unknown):never{let code="";if(record(v)&&record(v.error)&&typeof v.error.code==="string")code=v.error.code;const known:Record<string,SurveyAssignmentErrorCode>={AUTH_SESSION_EXPIRED:"AUTH_SESSION_EXPIRED",AUTH_CSRF_INVALID:"AUTH_CSRF_INVALID",LICENSE_OPERATION_DENIED:"LICENSE_OPERATION_DENIED",RESOURCE_NOT_FOUND:"RESOURCE_NOT_FOUND",PROJECT_ARCHIVED:"PROJECT_ARCHIVED",CONFLICT_VERSION:"CONFLICT_VERSION",CONFLICT_IDEMPOTENCY:"CONFLICT_IDEMPOTENCY",CONFLICT_STATE:"CONFLICT_STATE"};if(code==="VALIDATION_FAILED")throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INCOMPLETE");throw new SurveyAssignmentError(known[code]??(status===400||status===422?"SURVEY_ASSIGNMENT_INVALID_INPUT":"SURVEY_ASSIGNMENT_UNAVAILABLE"))}
function parents(projectId:string,roundId:string){if(!id(projectId)||!id(roundId))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INVALID_INPUT")}

export class SurveyAssignmentReadClient{constructor(private readonly fetcher:typeof fetch=globalThis.fetch.bind(globalThis)){}
 async #get(path:string){let r:Response;try{r=await this.fetcher(path,{method:"GET",credentials:"same-origin",cache:"no-store",redirect:"error",headers:{Accept:"application/json"}})}catch{throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE")}const v=await payload(r);if(!r.ok)failure(r.status,v);return{r,e:envelope(v)}}
 async list(projectId:string,roundId:string,pageSize=50,next:SurveyAssignmentCursor|null=null):Promise<SurveyAssignmentPage>{parents(projectId,roundId);if(!integer(pageSize,1)||pageSize>200||next!==null&&!cursor.test(next))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INVALID_INPUT");const q=new URLSearchParams({page_size:String(pageSize)});if(next)q.set("cursor",next);const{e}=await this.#get(`/api/v1/projects/${projectId}/survey-rounds/${roundId}/assignments?${q}`);const d=e.data;if(!record(d)||!exact(d,["items","next_cursor","has_more"])||!Array.isArray(d.items)||d.items.length>pageSize||typeof d.has_more!=="boolean"||d.has_more!==(d.next_cursor!==null)||d.next_cursor!==null&&(typeof d.next_cursor!=="string"||!cursor.test(d.next_cursor)))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");const items=d.items.map(x=>parseSurveyAssignment(x,projectId,roundId));if(new Set(items.map(x=>x.survey_assignment_id)).size!==items.length||items.some((x,i)=>i>0&&(x.created_at>items[i-1]!.created_at||x.created_at===items[i-1]!.created_at&&x.survey_assignment_id>=items[i-1]!.survey_assignment_id)))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return Object.freeze({items:Object.freeze(items),next_cursor:d.next_cursor as SurveyAssignmentCursor|null,has_more:d.has_more})}
 async get(projectId:string,roundId:string,assignmentId:string){parents(projectId,roundId);if(!id(assignmentId))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INVALID_INPUT");const{r,e}=await this.#get(`/api/v1/projects/${projectId}/survey-rounds/${roundId}/assignments/${assignmentId}`);const item=parseSurveyAssignment(e.data,projectId,roundId,assignmentId,true);if(r.headers.get("ETag")!==item.etag)throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return item}}

export class SurveyAssignmentWriteClient{constructor(private readonly session:SessionClient){if(!(session instanceof SessionClient))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INVALID_INPUT")}
 async #send(projectId:string,roundId:string,assignmentId:string|null,operation:"create"|"response"|"submit"|"validate"|"return",body:unknown|null,etagValue:string|null,key:string){parents(projectId,roundId);if(assignmentId!==null&&!id(assignmentId)||etagValue!==null&&!etag.test(etagValue)||!/^[\x20-\x7e]{16,128}$/.test(key))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INVALID_INPUT");let r:Response;try{r=await this.session.writeProjectSurveyAssignment(projectId,roundId,assignmentId,operation,body===null?null:JSON.stringify(body),etagValue,key)}catch(e){if(e instanceof SessionClientError&&(e.code==="AUTH_RELOGIN_REQUIRED"||e.code==="AUTH_CLIENT_BUSY"))throw new SurveyAssignmentError(e.code);throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE")}const v=await payload(r);if(!r.ok)failure(r.status,v);const data=envelope(v).data;const header=r.headers.get("ETag");const bodyEtag=record(data)?(operation==="response"?data.assignment_etag:data.etag):null;if(r.status!==(operation==="create"||operation==="response"?201:200)||header===null||bodyEtag!==header)throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return data}
 async create(projectId:string,roundId:string,departmentId:string,assigneeUserId:string|null,key:string){if(!id(departmentId)||!optionalId(assigneeUserId))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INVALID_INPUT");const data=await this.#send(projectId,roundId,null,"create",{department_id:departmentId,assignee_user_id:assigneeUserId},null,key);const item=parseSurveyAssignment(data,projectId,roundId);return item}
 async record(projectId:string,roundId:string,assignmentId:string,etagValue:string,input:SurveyResponseInput,key:string){if(!record(input)||!exact(input,["question_id","response_source","raw_answer","answer_value","evidence_ids","project_record_evidence_id","correction_of_response_id"])||!id(input.question_id)||(input.response_source!=="SELF_SERVICE"&&input.response_source!=="FACILITATED_RECORD")||!optionalText(input.raw_answer,20000)||!Array.isArray(input.evidence_ids)||input.evidence_ids.length>50||input.evidence_ids.some(x=>!id(x))||new Set(input.evidence_ids).size!==input.evidence_ids.length||!optionalId(input.project_record_evidence_id)||!optionalId(input.correction_of_response_id)||(input.response_source==="SELF_SERVICE")!==(input.project_record_evidence_id===null))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INVALID_INPUT");const data=await this.#send(projectId,roundId,assignmentId,"response",input,etagValue,key);const fields=["survey_response_id","survey_answer_id","survey_assignment_id","survey_round_id","survey_version_id","project_id","question_id","response_source","round_source_record_ref_id","correction_of_response_id","recorded_by","recorded_at","assignment_state","assignment_etag","evidence_count"];if(!record(data)||!exact(data,fields)||!id(data.survey_response_id)||!id(data.survey_answer_id)||data.survey_assignment_id!==assignmentId||data.survey_round_id!==roundId||!id(data.survey_version_id)||data.project_id!==projectId||data.question_id!==input.question_id||data.response_source!==input.response_source||!optionalId(data.round_source_record_ref_id)||!optionalId(data.correction_of_response_id)||!id(data.recorded_by)||!instant(data.recorded_at)||data.assignment_state!=="IN_PROGRESS"||typeof data.assignment_etag!=="string"||!etag.test(data.assignment_etag)||!integer(data.evidence_count)||data.evidence_count<input.evidence_ids.length)throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return Object.freeze({...data})}
 async #transition(projectId:string,roundId:string,assignmentId:string,operation:"submit"|"validate"|"return",etagValue:string,key:string,comment:string|null){const data=await this.#send(projectId,roundId,assignmentId,operation,comment===null?null:{comment},etagValue,key);const review=operation!=="submit";const fields=review?["survey_assignment_id","survey_round_id","project_id","state","etag","return_comment"]:["survey_assignment_id","survey_round_id","project_id","state","etag"];const expected=operation==="submit"?"SUBMITTED":operation==="validate"?"VALIDATED":"RETURNED";if(!record(data)||!exact(data,fields)||data.survey_assignment_id!==assignmentId||data.survey_round_id!==roundId||data.project_id!==projectId||data.state!==expected||typeof data.etag!=="string"||!etag.test(data.etag)||review&&data.return_comment!==comment)throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_UNAVAILABLE");return Object.freeze({...data}) as unknown as SurveyAssignmentReceipt}
 submit(projectId:string,roundId:string,assignmentId:string,etagValue:string,key:string){return this.#transition(projectId,roundId,assignmentId,"submit",etagValue,key,null)}
 validate(projectId:string,roundId:string,assignmentId:string,etagValue:string,key:string){return this.#transition(projectId,roundId,assignmentId,"validate",etagValue,key,null)}
 async returnAssignment(projectId:string,roundId:string,assignmentId:string,etagValue:string,key:string,comment:string){if(typeof comment!=="string"||comment.length<1||comment.length>2000||comment.trim()!==comment||/\p{C}/u.test(comment))throw new SurveyAssignmentError("SURVEY_ASSIGNMENT_INVALID_INPUT");return await this.#transition(projectId,roundId,assignmentId,"return",etagValue,key,comment)}}
