import { flushPromises,mount,type VueWrapper } from "@vue/test-utils";import{createMemoryHistory}from"vue-router";import{afterEach,describe,expect,it,vi}from"vitest";
import{createAppRouter}from"@/app/router";import{SessionClient}from"@/modules/auth/api/sessionClient";import{ProjectMemberReadClient,type ProjectMemberView}from"@/modules/project/api/projectMemberReadClient";import{RequirementReadClient,type RequirementView}from"@/modules/requirement/api/requirementReadClient";import{RequirementVersionWriteClient}from"@/modules/requirement/api/requirementVersionWriteClient";import View from"./ProjectRequirementDraftView.vue";
const project="01234567-89ab-4cde-8123-456789abcdef",requirement="11234567-89ab-4cde-8123-456789abcdef",version="21234567-89ab-4cde-8123-456789abcdef",actor="31234567-89ab-4cde-8123-456789abcdef",reviewer="41234567-89ab-4cde-8123-456789abcdef",evidence="51234567-89ab-4cde-8123-456789abcdef",trace="61234567-89ab-4cde-8123-456789abcdef",now="2026-10-08T12:00:00Z";
const root:RequirementView={requirement_id:requirement,project_id:project,requirement_code:"REQ-001",state:"ACTIVE",current_approved_version_ref:null,created_by:actor,created_at:now,updated_by:null,updated_at:now,etag:'"v0"'};
const member:ProjectMemberView={member_id:"71234567-89ab-4cde-8123-456789abcdef",user:{user_id:reviewer,display_name:"评审人"},role:"CUSTOMER_MANAGER",department:{department_id:"81234567-89ab-4cde-8123-456789abcdef",name:"客户部"},state:"ACTIVE",effective_at:now,ended_at:null,etag:'"v0"'};
function env(data:unknown){return new Response(JSON.stringify({data,trace_id:trace}),{headers:{"Content-Type":"application/json"}})}async function auth(){const s=new SessionClient(vi.fn().mockResolvedValue(env({user:{user_id:actor,username_display:"项目经理"},deployment_role:"NONE",password_change_required:false,authorized_projects:[{project_id:project,name:"项目",role:"PROJECT_MANAGER"}],absolute_expires_at:"2030-01-01T12:00:00Z",idle_expires_at:"2030-01-01T11:00:00Z",csrf_token:"a".repeat(64)}))as typeof fetch);await s.login("user","synthetic");return s;}
function clients(session:SessionClient){const requirements=new RequirementReadClient(vi.fn()as typeof fetch);vi.spyOn(requirements,"getRequirement").mockResolvedValue(root);vi.spyOn(requirements,"listVersions").mockResolvedValue({items:[],next_cursor:null,has_more:false});const members=new ProjectMemberReadClient(vi.fn()as typeof fetch);vi.spyOn(members,"list").mockResolvedValue({items:[member],next_cursor:null,has_more:false});const writer=new RequirementVersionWriteClient(session);return{requirements,members,writer};}
async function view(session:SessionClient,bundle=clients(session)){const router=createAppRouter(createMemoryHistory());await router.push(`/projects/${project}/requirements/${requirement}/draft`);await router.isReady();const wrapper=mount(View,{props:{session,...bundle},global:{plugins:[router]}});await flushPromises();return{wrapper,...bundle};}
function field(wrapper:VueWrapper,text:string,selector="input,textarea,select"){const label=wrapper.findAll("label").find(x=>x.text().includes(text));if(!label)throw new Error(text);return label.get(selector);}
async function fill(wrapper:VueWrapper,classification="PENDING_CONFIRMATION"){await field(wrapper,"业务域").setValue("文档管理");await field(wrapper,"需求陈述","textarea").setValue("形成审批记录");await field(wrapper,"形成理由","textarea").setValue("已确认访谈");await field(wrapper,"分类","select").setValue(classification);await field(wrapper,"来源对象标识").setValue(evidence);await field(wrapper,"Evidence标识","textarea").setValue(evidence);await field(wrapper,"可观察结果").setValue("形成记录");await field(wrapper,"验证方法").setValue("审批测试");await field(wrapper,"所需数据").setValue("档案");await field(wrapper,"证据要求").setValue("审计记录");await field(wrapper,"本次创建原因","textarea").setValue("形成需求草稿");await wrapper.get(".confirm input").setValue(true);}
describe("ProjectRequirementDraftView",()=>{afterEach(()=>vi.restoreAllMocks());
it("does not load or show a form without a write session",async()=>{const session=new SessionClient(vi.fn()as typeof fetch);const bundle=clients(session);const result=await view(session,bundle);expect(result.wrapper.text()).toContain("尚未读取当前身份");expect(result.requirements.getRequirement).not.toHaveBeenCalled();expect(result.wrapper.find("form").exists()).toBe(false);result.wrapper.unmount();});
it("shows structured maintenance guidance and sends no source body",async()=>{const session=await auth();const result=await view(session);expect(result.wrapper.text()).toContain("页面不要求复制原文");expect(result.wrapper.text()).toContain("逐项维护五要素");expect(result.wrapper.text()).toContain("只有人工核对能力基线后填写");expect(result.wrapper.text()).toContain("每行一项");expect(result.wrapper.find("form").exists()).toBe(true);result.wrapper.unmount();});
it("creates, validates, and blocks a pending-confirmation version from review",async()=>{const session=await auth();const bundle=clients(session);vi.spyOn(bundle.writer,"create").mockResolvedValue({requirement_version_id:version,requirement_id:requirement,project_id:project,version_no:1,state:"DRAFT",content_fingerprint:"a".repeat(64),supersedes_version_ref:null,created_by:actor,created_at:now,requirement_etag:'"v1"'});vi.spyOn(bundle.writer,"validate").mockResolvedValue({audit_event_id:trace,requirement_id:requirement,requirement_version_id:version,project_id:project,version_no:1,state:"DRAFT",classification:"PENDING_CONFIRMATION",valid:true,blocking_issues:[],warnings:[],coverage_summary:{sources:1,acceptance_criteria:1,capability_assessments:0,assumptions:0,exclusions:0,dependencies:0,evidence_refs:1},checked_at:now});const result=await view(session,bundle);await fill(result.wrapper);await result.wrapper.get("form").trigger("submit");await flushPromises();expect(bundle.writer.create).toHaveBeenCalledWith(project,requirement,'"v0"',expect.objectContaining({classification:"PENDING_CONFIRMATION",sources:[expect.objectContaining({source_object_id:evidence})],acceptance_criteria:[expect.objectContaining({required_environment:"Windows 11"})]}),expect.stringMatching(/^requirement-version-/));await result.wrapper.findAll("button").find(x=>x.text().includes("完整校验"))!.trigger("click");await flushPromises();expect(result.wrapper.text()).toContain("待确认项不可送审");expect(result.wrapper.text()).not.toContain("提交正式评审");result.wrapper.unmount();});
it("submits a validated non-pending version using selected active member",async()=>{const session=await auth();const bundle=clients(session);vi.spyOn(bundle.writer,"create").mockResolvedValue({requirement_version_id:version,requirement_id:requirement,project_id:project,version_no:1,state:"DRAFT",content_fingerprint:"a".repeat(64),supersedes_version_ref:null,created_by:actor,created_at:now,requirement_etag:'"v1"'});vi.spyOn(bundle.writer,"validate").mockResolvedValue({audit_event_id:trace,requirement_id:requirement,requirement_version_id:version,project_id:project,version_no:1,state:"DRAFT",classification:"STANDARD_FUNCTION",valid:true,blocking_issues:[],warnings:[],coverage_summary:{sources:1,acceptance_criteria:1,capability_assessments:0,assumptions:0,exclusions:0,dependencies:0,evidence_refs:1},checked_at:now});vi.spyOn(bundle.writer,"submitReview").mockResolvedValue({review_id:trace,review_round_id:evidence,subject_type:"REQ-03",project_id:project,requirement_id:requirement,requirement_version_id:version,policy_ref:"REQUIREMENT_ALL_V1",reviewer_ids:[reviewer],state:"IN_REVIEW",round_no:1,review_etag:'"v1"',submitted_by:actor,submitted_at:now});const result=await view(session,bundle);await fill(result.wrapper,"STANDARD_FUNCTION");await result.wrapper.get("form").trigger("submit");await flushPromises();await result.wrapper.findAll("button").find(x=>x.text().includes("完整校验"))!.trigger("click");await flushPromises();await field(result.wrapper,"评审人","input[type=checkbox]").setValue(true);await result.wrapper.findAll("button").find(x=>x.text()==="提交正式评审")!.trigger("click");await flushPromises();expect(bundle.writer.submitReview).toHaveBeenCalledWith(project,requirement,version,[reviewer],expect.stringMatching(/^requirement-review-/));expect(result.wrapper.text()).toContain("这不是批准结论");result.wrapper.unmount();});
});
