<script setup lang="ts">
import { computed, inject, onUnmounted, reactive, ref, toRaw, watch } from "vue";
import { RouterLink, useRoute } from "vue-router";
import { SessionClient } from "@/modules/auth/api/sessionClient";
import { sessionClientKey } from "@/modules/auth/api/sessionContext";
import { ProjectMemberReadClient, type ProjectMemberView } from "@/modules/project/api/projectMemberReadClient";
import { RequirementReadClient, type RequirementVersionSummary, type RequirementView } from "@/modules/requirement/api/requirementReadClient";
import { RequirementVersionWriteClient, RequirementVersionWriteError, type CreatedRequirementVersion,
  type RequirementValidationReport, type RequirementReviewSubmission, type RequirementVersionCreateInput } from "@/modules/requirement/api/requirementVersionWriteClient";

const props=defineProps<{session?:SessionClient;requirements?:RequirementReadClient;members?:ProjectMemberReadClient;writer?:RequirementVersionWriteClient}>();
const session=toRaw(props.session??inject(sessionClientKey,null)??new SessionClient()); const requirements=toRaw(props.requirements??new RequirementReadClient());
const members=toRaw(props.members??new ProjectMemberReadClient()); const writer=toRaw(props.writer??new RequirementVersionWriteClient(session));
const identity=session.view; const route=useRoute(); const root=ref<RequirementView|null>(null); const versions=ref<readonly RequirementVersionSummary[]>([]);
const reviewers=ref<readonly ProjectMemberView[]>([]); const selectedReviewers=ref<string[]>([]); const busy=ref(false); const error=ref(""); const notice=ref("");
const created=ref<CreatedRequirementVersion|null>(null); const report=ref<RequirementValidationReport|null>(null); const submitted=ref<RequirementReviewSubmission|null>(null);
const confirmed=ref(false); let generation=0; let mounted=true;
type SourceDraft={source_type:RequirementVersionCreateInput["sources"][number]["source_type"];source_object_id:string;source_version_ref:string;evidence_refs:string};
type CriterionDraft={observable_result:string;verification_method:string;required_data:string;required_environment:string;evidence_requirement:string};
type CapabilityDraft={baseline_version_id:string;capability_item_id:string;match_type:RequirementVersionCreateInput["capability_assessments"][number]["match_type"];fit_gap:string;constraints_text:string;confirmation_state:RequirementVersionCreateInput["capability_assessments"][number]["confirmation_state"];standard_evidence_id:string;project_evidence_id:string};
const form=reactive({title:"",statement:"",rationale:"",domain_name:"",priority:"MEDIUM" as RequirementVersionCreateInput["priority"],risk:"MEDIUM" as RequirementVersionCreateInput["risk"],classification:"PENDING_CONFIRMATION" as RequirementVersionCreateInput["classification"],base_version_ref:"",client_reason:"",assumptions:"",exclusions:"",dependencies:"",ai_task_refs:"",sources:[{source_type:"PROJECT_EVIDENCE",source_object_id:"",source_version_ref:"",evidence_refs:""}] as SourceDraft[],criteria:[{observable_result:"",verification_method:"",required_data:"",required_environment:"Windows 11",evidence_requirement:""}] as CriterionDraft[],capabilities:[] as CapabilityDraft[]});
const projectId=()=>typeof route.params.projectId==="string"?route.params.projectId:""; const requirementId=()=>typeof route.params.requirementId==="string"?route.params.requirementId:"";
const canWrite=computed(()=>!!identity&&!identity.password_change_required&&session.canSubmit&&session.view?.user.user_id===identity.user.user_id&&session.view.authorized_projects.some(p=>p.project_id===projectId()&&(p.role==="PROJECT_MANAGER"||p.role==="IMPLEMENTATION_MEMBER")));
const split=(v:string)=>v.split(/[,\n]/).map(x=>x.trim()).filter(Boolean); const lines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);
function addSource(){form.sources.push({source_type:"PROJECT_EVIDENCE",source_object_id:"",source_version_ref:"",evidence_refs:""});confirmed.value=false;}
function addCriterion(){form.criteria.push({observable_result:"",verification_method:"",required_data:"",required_environment:"Windows 11",evidence_requirement:""});confirmed.value=false;}
function addCapability(){form.capabilities.push({baseline_version_id:"",capability_item_id:"",match_type:"UNKNOWN",fit_gap:"",constraints_text:"",confirmation_state:"CANDIDATE",standard_evidence_id:"",project_evidence_id:""});confirmed.value=false;}
async function load(){if(!identity||identity.password_change_required)return;const p=projectId(),r=requirementId(),current=++generation;busy.value=true;error.value="";root.value=null;versions.value=[];reviewers.value=[];try{const[a,b,c]=await Promise.all([requirements.getRequirement(p,r),requirements.listVersions(p,r),members.list(p)]);if(!mounted||current!==generation||p!==projectId()||r!==requirementId())return;root.value=a;versions.value=b.items;reviewers.value=Object.freeze(c.items.filter(x=>x.state==="ACTIVE"&&x.user.user_id!==identity.user.user_id));form.base_version_ref=a.current_approved_version_ref??"";}catch(e){if(mounted&&current===generation)error.value=e instanceof Error?e.message:"暂时无法准备需求草稿。";}finally{if(mounted&&current===generation)busy.value=false;}}
function input():RequirementVersionCreateInput{return{initial:form.base_version_ref==="",base_version_ref:form.base_version_ref||null,title:form.title.trim()||null,statement:form.statement.trim(),rationale:form.rationale.trim(),domain_name:form.domain_name.trim(),priority:form.priority,risk:form.risk,classification:form.classification,sources:form.sources.map(s=>({source_type:s.source_type,source_object_id:s.source_object_id.trim(),source_version_ref:s.source_version_ref.trim()||null,evidence_refs:split(s.evidence_refs)})),acceptance_criteria:form.criteria.map(x=>({observable_result:x.observable_result.trim(),verification_method:x.verification_method.trim(),required_data:x.required_data.trim(),required_environment:x.required_environment.trim(),evidence_requirement:x.evidence_requirement.trim()})),capability_assessments:form.capabilities.map(x=>({baseline_version_id:x.baseline_version_id.trim(),capability_item_id:x.capability_item_id.trim(),match_type:x.match_type,fit_gap:x.fit_gap.trim(),constraints_text:x.constraints_text.trim(),assessor_kind:"HUMAN" as const,confirmation_state:x.confirmation_state,evidence_refs:[{evidence_id:x.standard_evidence_id.trim(),evidence_role:"STANDARD"},{evidence_id:x.project_evidence_id.trim(),evidence_role:"PROJECT"}]})),assumptions:lines(form.assumptions),exclusions:lines(form.exclusions),dependencies:lines(form.dependencies),ai_task_refs:lines(form.ai_task_refs),client_reason:form.client_reason.trim()};}
async function create(){if(!canWrite.value||!root.value||!confirmed.value||busy.value)return;const current=++generation,p=projectId(),r=requirementId(),key=`requirement-version-${crypto.randomUUID()}`;busy.value=true;error.value="";notice.value="";confirmed.value=false;try{const result=await writer.create(p,r,root.value.etag,input(),key);if(!mounted||current!==generation)return;created.value=result;notice.value="草稿已创建。请先运行服务端校验；校验通过且不是待确认项后才能送审。";}catch(e){if(mounted&&current===generation){error.value=e instanceof RequirementVersionWriteError?e.message:"暂时无法确认创建结果。";notice.value=e instanceof RequirementVersionWriteError&&e.uncertain?"结果可能已经提交，请返回需求详情核对版本和审计，不要生成新的重复操作。":"";}}finally{if(mounted&&current===generation)busy.value=false;}}
async function validate(){if(!canWrite.value||!created.value||busy.value)return;const current=++generation;busy.value=true;error.value="";try{const value=await writer.validate(projectId(),requirementId(),created.value.requirement_version_id,`requirement-validate-${crypto.randomUUID()}`);if(mounted&&current===generation){report.value=value;notice.value=value.valid?"服务端校验通过；请选择评审人后送审。":"校验未通过，请按阻断项新建修正版；固定版本不可覆盖。";}}catch(e){if(mounted&&current===generation)error.value=e instanceof Error?e.message:"暂时无法确认校验结果。";}finally{if(mounted&&current===generation)busy.value=false;}}
async function submit(){if(!canWrite.value||!created.value||!report.value?.valid||form.classification==="PENDING_CONFIRMATION"||!selectedReviewers.value.length||busy.value)return;const current=++generation;busy.value=true;error.value="";try{const value=await writer.submitReview(projectId(),requirementId(),created.value.requirement_version_id,selectedReviewers.value,`requirement-review-${crypto.randomUUID()}`);if(mounted&&current===generation){submitted.value=value;notice.value="需求版本已进入正式评审；当前回执不代表评审通过。";}}catch(e){if(mounted&&current===generation)error.value=e instanceof Error?e.message:"暂时无法确认送审结果。";}finally{if(mounted&&current===generation)busy.value=false;}}
watch(()=>[route.params.projectId,route.params.requirementId],()=>{generation+=1;created.value=null;report.value=null;submitted.value=null;notice.value="";error.value="";void load();},{immediate:true});
onUnmounted(()=>{mounted=false;generation+=1;});
</script>

<template><section class="draft" aria-labelledby="draft-title"><p class="section-kicker">项目需求</p><h1 id="draft-title">创建结构化需求版本草稿</h1>
  <p class="warning"><strong>不要把AI建议或模板直接当成客户事实。</strong>只填写已核对的信息，并用固定来源与Evidence引用建立追溯；页面不要求复制原文。</p>
  <p><RouterLink :to="{name:'project-requirement-detail',params:{projectId:route.params.projectId,requirementId:route.params.requirementId}}">返回需求详情</RouterLink></p>
  <p v-if="!identity" role="status">尚未读取当前身份，请先登录。</p><p v-else-if="!canWrite" role="status">当前会话没有写入证明或项目角色不允许创建需求版本，请重新登录或联系项目负责人。</p>
  <template v-else-if="root"><form v-if="!created" @submit.prevent="create"><fieldset><legend>基本信息</legend>
    <label>标题（可选）<input v-model="form.title" maxlength="255"></label><label>业务域<input v-model="form.domain_name" required maxlength="255"></label>
    <label>需求陈述<textarea v-model="form.statement" required maxlength="20000"></textarea><small>描述需要实现的可验证业务结果，不粘贴整段原文。</small></label>
    <label>形成理由<textarea v-model="form.rationale" required maxlength="20000"></textarea><small>说明为何形成该需求及人工判断依据。</small></label>
    <label>分类<select v-model="form.classification"><option value="STANDARD_FUNCTION">标准功能</option><option value="NONSTANDARD_FUNCTION">非标功能</option><option value="DIFFERENCE">差异项</option><option value="PENDING_CONFIRMATION">待确认项</option></select></label>
    <label>优先级<select v-model="form.priority"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><label>风险<select v-model="form.risk"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label>
    <label>基线版本<select v-model="form.base_version_ref"><option value="">首版（仅无既有版本时选择）</option><option v-for="v in versions" :key="v.requirement_version_id" :value="v.requirement_version_id">版本 {{v.version_no}} · {{v.title??v.domain_name}}</option></select></label></fieldset>
    <fieldset><legend>固定来源</legend><p>对象标识来自已确认调研结论、交接记录或Evidence；不要在这里复制正文。</p><article v-for="(s,i) in form.sources" :key="i"><label>来源类型<select v-model="s.source_type"><option>APPROVED_SURVEY_CONCLUSION</option><option>CONFIRMED_HANDOVER</option><option>HUMAN_DECISION</option><option>PROJECT_EVIDENCE</option></select></label><label>来源对象标识<input v-model="s.source_object_id" required></label><label>固定版本标识（交接来源必填）<input v-model="s.source_version_ref"></label><label>Evidence标识（逗号或换行分隔）<textarea v-model="s.evidence_refs"></textarea></label></article><button type="button" @click="addSource">增加来源</button></fieldset>
    <fieldset><legend>验收标准：逐项维护五要素</legend><article v-for="(c,i) in form.criteria" :key="i"><label>可观察结果<input v-model="c.observable_result" required></label><label>验证方法<input v-model="c.verification_method" required></label><label>所需数据<input v-model="c.required_data" required></label><label>所需环境<input v-model="c.required_environment" required></label><label>证据要求<input v-model="c.evidence_requirement" required></label></article><button type="button" @click="addCriterion">增加验收标准</button></fieldset>
    <fieldset><legend>标准能力人工评估（可选）</legend><p>只有人工核对能力基线后填写；AI不得作为评估人。每项必须同时提供标准能力证据和项目事实证据。</p><article v-for="(c,i) in form.capabilities" :key="i"><label>能力基线版本标识<input v-model="c.baseline_version_id" required></label><label>能力项标识<input v-model="c.capability_item_id" required></label><label>匹配类型<select v-model="c.match_type"><option>DIRECT</option><option>PARTIAL</option><option>NONE</option><option>UNKNOWN</option></select></label><label>Fit/Gap说明<textarea v-model="c.fit_gap" required></textarea></label><label>约束说明<textarea v-model="c.constraints_text" required></textarea></label><label>人工确认状态<select v-model="c.confirmation_state"><option>CANDIDATE</option><option>CONFIRMED</option><option>REJECTED</option></select></label><label>标准能力Evidence标识<input v-model="c.standard_evidence_id" required></label><label>项目事实Evidence标识<input v-model="c.project_evidence_id" required></label></article><button type="button" @click="addCapability">增加能力评估</button></fieldset>
    <fieldset><legend>边界与辅助引用</legend><label>假设（每行一项）<textarea v-model="form.assumptions"></textarea></label><label>排除项（每行一项）<textarea v-model="form.exclusions"></textarea></label><label>依赖（每行一项）<textarea v-model="form.dependencies"></textarea></label><label>AI任务标识（每行一项，仅作追溯）<textarea v-model="form.ai_task_refs"></textarea></label><label>本次创建原因<textarea v-model="form.client_reason" required maxlength="2000"></textarea></label></fieldset>
    <label class="confirm"><input v-model="confirmed" type="checkbox">我已核对来源、验收五要素和人工判断；未把AI建议直接确认为业务事实。</label><button :disabled="busy||!confirmed">创建不可变草稿版本</button></form>
    <section v-else><h2>草稿创建回执</h2><p>版本 {{created.version_no}} · {{created.requirement_version_id}}</p><button :disabled="busy" @click="validate">运行服务端完整校验</button>
      <div v-if="report"><p><strong>校验：{{report.valid?'通过':'未通过'}}</strong></p><ul><li v-for="x in report.blocking_issues" :key="x">{{x}}</li></ul></div>
      <fieldset v-if="report?.valid"><legend>正式送审</legend><p v-if="form.classification==='PENDING_CONFIRMATION'" class="warning">待确认项不可送审；请先核实后创建修正版。</p><template v-else><label v-for="m in reviewers" :key="m.user.user_id"><input v-model="selectedReviewers" type="checkbox" :value="m.user.user_id">{{m.user.display_name}}（{{m.role}}）</label><button :disabled="busy||!selectedReviewers.length||!!submitted" @click="submit">提交正式评审</button></template></fieldset>
      <p v-if="submitted">已创建评审 {{submitted.review_id}}，状态为评审中；这不是批准结论。</p></section>
  </template><p v-if="busy" role="status">正在处理…</p><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p></section></template>

<style scoped>.draft{max-width:68rem;margin:1rem auto;padding:1.5rem;background:#fff;border-radius:1rem}.draft form,.draft fieldset,.draft article,.draft label{display:grid;gap:.4rem}.draft form,.draft fieldset{gap:1rem}.draft fieldset{margin:1rem 0;padding:1rem}.draft article{padding:1rem;border:1px solid #d8dee7;border-radius:.7rem}.draft textarea{min-height:5rem}.warning{padding:.8rem 1rem;border-left:.3rem solid #d29b42;background:#fff8e9}.confirm{display:flex!important;align-items:flex-start}.draft [role=alert]{color:#a21d25}</style>
